/********************************************************************************
** Form generated from reading UI file 'oshstudio.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_OSHSTUDIO_H
#define UI_OSHSTUDIO_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include "osha2bw.h"
#include "oshaxiswca.h"
#include "oshbuttonw.h"
#include "oshpincombobox.h"
#include "oshshapesw.h"
#include "oshsingenc.h"

QT_BEGIN_NAMESPACE

class Ui_OSHStudio
{
public:
    QWidget *centralWidget;
    QPushButton *getConfig_button;
    QLabel *label_35;
    QLabel *label_DevDescImg;
    QLabel *label_DevDesc;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QLabel *label_B11;
    QLabel *label_A11;
    QLabel *label_A3;
    QLabel *label_B13;
    QLabel *label_A6;
    QLabel *label_B15;
    QLabel *label_B3;
    QLabel *label_B5;
    QLabel *label_A15;
    QGroupBox *groupBox;
    QLabel *labelHelp;
    QLabel *label_C14;
    QLabel *label_B6;
    QLabel *label_A2;
    QLabel *label_B1;
    QLabel *label_B7;
    QLabel *label_A0;
    QLabel *label_A4;
    QLabel *label_A7;
    QLabel *label_B8;
    QLabel *label_A9;
    QLabel *label_B0;
    QLabel *label;
    QLabel *label_C15;
    QLabel *label_A5;
    QLabel *label_B4;
    QLabel *label_B12;
    QLabel *label_A8;
    QLabel *label_B14;
    QLabel *label_A1;
    QLabel *label_B9;
    QLabel *label_A10;
    QLabel *label_A12;
    QLabel *label_C13;
    QLabel *label_B10;
    QLabel *label_3;
    QComboBox *comboBox_BoardType;
    oshpincombobox *widget_PB25;
    oshpincombobox *widget_PB0;
    oshpincombobox *widget_PB1;
    oshpincombobox *widget_PB2;
    oshpincombobox *widget_PB3;
    oshpincombobox *widget_PB4;
    oshpincombobox *widget_PB5;
    oshpincombobox *widget_PB6;
    oshpincombobox *widget_PB7;
    oshpincombobox *widget_PB8;
    oshpincombobox *widget_PB9;
    oshpincombobox *widget_PB10;
    oshpincombobox *widget_PB11;
    oshpincombobox *widget_PB12;
    oshpincombobox *widget_PB13;
    oshpincombobox *widget_PB14;
    oshpincombobox *widget_PB15;
    oshpincombobox *widget_PB16;
    oshpincombobox *widget_PB17;
    oshpincombobox *widget_PB18;
    oshpincombobox *widget_PB19;
    oshpincombobox *widget_PB20;
    oshpincombobox *widget_PB21;
    oshpincombobox *widget_PB22;
    oshpincombobox *widget_PB23;
    oshpincombobox *widget_PB24;
    oshpincombobox *widget_PB26;
    oshpincombobox *widget_PB27;
    oshpincombobox *widget_PB28;
    oshpincombobox *widget_PB29;
    oshpincombobox *widget_PB30;
    oshpincombobox *widget_PB31;
    QWidget *tab;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QCheckBox *checkBox_AxisComb;
    QComboBox *comboBox_AxisCombBegin;
    QComboBox *comboBox_AxisCombEnd;
    QSlider *horizontalSliderAxisComb;
    QLabel *label_AxisComb1;
    QLabel *label_AxisComb2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_AxisCombPin1;
    QLabel *label_AxisCombPin2;
    QRadioButton *radioButtonCoopwoork;
    QRadioButton *radioButtonEachonhisown;
    OSHaxiswca *widget_axis1;
    OSHaxiswca *widget_axis2;
    OSHaxiswca *widget_axis3;
    OSHaxiswca *widget_axis4;
    OSHaxiswca *widget_axis5;
    OSHaxiswca *widget_axis6;
    OSHaxiswca *widget_axisComb1;
    OSHaxiswca *widget_axisComb2;
    QWidget *tab_7;
    oshshapesw *widget_AS_big;
    QComboBox *comboBox_curr_shape_prof;
    QLabel *label_2;
    QLabel *label_8;
    QComboBox *comboBox_shape_axis_1;
    QLabel *label_9;
    QComboBox *comboBox_shape_axis_2;
    QLabel *label_10;
    QComboBox *comboBox_shape_axis_3;
    QLabel *label_11;
    QComboBox *comboBox_shape_axis_4;
    QLabel *label_12;
    QComboBox *comboBox_shape_axis_5;
    QLabel *label_13;
    QComboBox *comboBox_shape_axis_6;
    oshshapesw *widget_AS_1;
    oshshapesw *widget_AS_2;
    oshshapesw *widget_AS_3;
    oshshapesw *widget_AS_4;
    oshshapesw *widget_AS_5;
    oshshapesw *widget_AS_6;
    QLabel *label_Prof_1;
    QLabel *label_Prof_2;
    QLabel *label_Prof_3;
    QLabel *label_Prof_4;
    QLabel *label_Prof_5;
    QLabel *label_Prof_6;
    QLabel *label_Prof_CustName_1;
    QLabel *label_Prof_CustName_2;
    QLabel *label_Prof_CustName_3;
    QLabel *label_Prof_CustName_4;
    QLabel *label_Prof_CustName_5;
    QLabel *label_Prof_CustName_6;
    QLabel *label_14;
    QWidget *tab_3;
    QLabel *label_POV1;
    QLabel *label_POV2;
    QLabel *label_POV3;
    QLabel *label_POV4;
    oshbuttonw *widget_SB_1;
    oshbuttonw *widget_SB_2;
    oshbuttonw *widget_SB_3;
    oshbuttonw *widget_SB_4;
    oshbuttonw *widget_SB_5;
    oshbuttonw *widget_SB_6;
    oshbuttonw *widget_SB_7;
    oshbuttonw *widget_SB_8;
    oshbuttonw *widget_SB_9;
    oshbuttonw *widget_SB_10;
    oshbuttonw *widget_SB_11;
    oshbuttonw *widget_SB_12;
    oshbuttonw *widget_SB_13;
    oshbuttonw *widget_SB_14;
    oshbuttonw *widget_SB_15;
    oshbuttonw *widget_SB_16;
    oshbuttonw *widget_SB_17;
    oshbuttonw *widget_SB_18;
    oshbuttonw *widget_SB_19;
    oshbuttonw *widget_SB_20;
    oshbuttonw *widget_SB_21;
    oshbuttonw *widget_SB_22;
    oshbuttonw *widget_SB_23;
    oshbuttonw *widget_SB_24;
    oshbuttonw *widget_SB_25;
    oshbuttonw *widget_SB_26;
    oshbuttonw *widget_SB_27;
    oshbuttonw *widget_SB_28;
    oshbuttonw *widget_SB_29;
    oshbuttonw *widget_SB_30;
    oshbuttonw *widget_SB_31;
    oshbuttonw *widget_SB_32;
    oshbuttonw *widget_SB_33;
    oshbuttonw *widget_SB_34;
    oshbuttonw *widget_SB_35;
    oshbuttonw *widget_SB_36;
    oshbuttonw *widget_SB_37;
    oshbuttonw *widget_SB_38;
    oshbuttonw *widget_SB_39;
    oshbuttonw *widget_SB_40;
    oshbuttonw *widget_SB_41;
    oshbuttonw *widget_SB_42;
    oshbuttonw *widget_SB_43;
    oshbuttonw *widget_SB_44;
    oshbuttonw *widget_SB_45;
    oshbuttonw *widget_SB_46;
    oshbuttonw *widget_SB_47;
    oshbuttonw *widget_SB_48;
    oshbuttonw *widget_SB_49;
    oshbuttonw *widget_SB_50;
    oshbuttonw *widget_SB_51;
    oshbuttonw *widget_SB_52;
    oshbuttonw *widget_SB_53;
    oshbuttonw *widget_SB_54;
    oshbuttonw *widget_SB_55;
    oshbuttonw *widget_SB_56;
    oshbuttonw *widget_SB_57;
    oshbuttonw *widget_SB_58;
    oshbuttonw *widget_SB_59;
    oshbuttonw *widget_SB_60;
    oshbuttonw *widget_SB_61;
    oshbuttonw *widget_SB_62;
    oshbuttonw *widget_SB_63;
    oshbuttonw *widget_SB_64;
    QGroupBox *groupBox_2;
    QLabel *labelHelp_SB;
    QLabel *label_POV1name;
    QLabel *label_POV2name;
    QLabel *label_POV3name;
    QLabel *label_POV4name;
    QWidget *tab_6;
    QLabel *label_ZeroA2B;
    osha2bw *widget_A2B_1;
    osha2bw *widget_A2B_2;
    osha2bw *widget_A2B_3;
    osha2bw *widget_A2B_4;
    osha2bw *widget_A2B_5;
    osha2bw *widget_A2B_6;
    osha2bw *widget_A2B_7;
    osha2bw *widget_A2B_8;
    osha2bw *widget_A2B_9;
    osha2bw *widget_A2B_10;
    QWidget *tab_5;
    QLabel *label_ZeroSglEncoders;
    QLabel *label_SEHelp;
    oshsingenc *widget_SE1;
    oshsingenc *widget_SE2;
    oshsingenc *widget_SE3;
    oshsingenc *widget_SE4;
    oshsingenc *widget_SE5;
    oshsingenc *widget_SE6;
    oshsingenc *widget_SE7;
    oshsingenc *widget_SE8;
    oshsingenc *widget_SE9;
    oshsingenc *widget_SE10;
    oshsingenc *widget_SE11;
    oshsingenc *widget_SE12;
    oshsingenc *widget_SE13;
    oshsingenc *widget_SE14;
    QWidget *tab_4;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QSpinBox *spinBox__Rot_Press_time;
    QSpinBox *spinBox_RotSwitch_Press_time;
    QSpinBox *spinBox_Rot_Debounce_time;
    QSpinBox *spinBox_Button_Debounce_time;
    QFrame *line;
    QSpinBox *spinBox_USB_exchange;
    QLabel *label_59;
    QLineEdit *lineEdit_Device_ident;
    QLabel *label_60;
    QSpinBox *spinBox_RotSwitch_min_time;
    QLabel *label_61;
    QSpinBox *spinBox_A2B_Press_time;
    QLabel *label_62;
    QSpinBox *spinBox_A2B_min_time;
    QLabel *label_63;
    QPushButton *saveConfig_Button;
    QPushButton *saveFile_Button;
    QPushButton *loadFile_Button;
    QLabel *label_34;
    QPushButton *resetConfig_button;
    QPushButton *restoreConfig_button;
    QLabel *label_Stud_version;
    QLabel *label_58;
    QLabel *label_Firmware_Vers;
    QPushButton *startLog_Button;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *OSHStudio)
    {
        if (OSHStudio->objectName().isEmpty())
            OSHStudio->setObjectName(QStringLiteral("OSHStudio"));
        OSHStudio->resize(1026, 590);
        OSHStudio->setMaximumSize(QSize(1026, 590));
        QIcon icon;
        icon.addFile(QStringLiteral(":/Images/openhardware.ico"), QSize(), QIcon::Normal, QIcon::Off);
        OSHStudio->setWindowIcon(icon);
        centralWidget = new QWidget(OSHStudio);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        getConfig_button = new QPushButton(centralWidget);
        getConfig_button->setObjectName(QStringLiteral("getConfig_button"));
        getConfig_button->setGeometry(QRect(10, 150, 151, 41));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        getConfig_button->setFont(font);
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 10, 141, 21));
        label_35->setFont(font);
        label_DevDescImg = new QLabel(centralWidget);
        label_DevDescImg->setObjectName(QStringLiteral("label_DevDescImg"));
        label_DevDescImg->setEnabled(true);
        label_DevDescImg->setGeometry(QRect(-10, 30, 71, 51));
        label_DevDescImg->setStyleSheet(QStringLiteral("image: url(:/Images/cropped-OK-big-green-button.png);"));
        label_DevDesc = new QLabel(centralWidget);
        label_DevDesc->setObjectName(QStringLiteral("label_DevDesc"));
        label_DevDesc->setEnabled(true);
        label_DevDesc->setGeometry(QRect(40, 30, 121, 51));
        label_DevDesc->setAlignment(Qt::AlignCenter);
        label_DevDesc->setWordWrap(true);
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(170, 30, 841, 541));
        QFont font1;
        font1.setPointSize(8);
        font1.setBold(true);
        font1.setWeight(75);
        tabWidget->setFont(font1);
        tabWidget->setLayoutDirection(Qt::LeftToRight);
        tabWidget->setAutoFillBackground(false);
        tabWidget->setStyleSheet(QStringLiteral("background-color: rgb(240, 240, 240);"));
        tabWidget->setTabPosition(QTabWidget::North);
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        label_B11 = new QLabel(tab_2);
        label_B11->setObjectName(QStringLiteral("label_B11"));
        label_B11->setGeometry(QRect(550, 60, 31, 16));
        QFont font2;
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        label_B11->setFont(font2);
        label_B11->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A11 = new QLabel(tab_2);
        label_A11->setObjectName(QStringLiteral("label_A11"));
        label_A11->setGeometry(QRect(20, 200, 31, 16));
        label_A11->setFont(font2);
        label_A11->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A3 = new QLabel(tab_2);
        label_A3->setObjectName(QStringLiteral("label_A3"));
        label_A3->setGeometry(QRect(550, 220, 31, 16));
        label_A3->setFont(font2);
        label_A3->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B13 = new QLabel(tab_2);
        label_B13->setObjectName(QStringLiteral("label_B13"));
        label_B13->setGeometry(QRect(20, 80, 31, 16));
        label_B13->setFont(font2);
        label_B13->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A6 = new QLabel(tab_2);
        label_A6->setObjectName(QStringLiteral("label_A6"));
        label_A6->setGeometry(QRect(550, 160, 31, 16));
        label_A6->setFont(font2);
        label_A6->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B15 = new QLabel(tab_2);
        label_B15->setObjectName(QStringLiteral("label_B15"));
        label_B15->setGeometry(QRect(20, 120, 31, 16));
        label_B15->setFont(font2);
        label_B15->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B3 = new QLabel(tab_2);
        label_B3->setObjectName(QStringLiteral("label_B3"));
        label_B3->setGeometry(QRect(20, 260, 31, 16));
        label_B3->setFont(font2);
        label_B3->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B5 = new QLabel(tab_2);
        label_B5->setObjectName(QStringLiteral("label_B5"));
        label_B5->setGeometry(QRect(20, 300, 31, 16));
        label_B5->setFont(font2);
        label_B5->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A15 = new QLabel(tab_2);
        label_A15->setObjectName(QStringLiteral("label_A15"));
        label_A15->setGeometry(QRect(20, 240, 31, 16));
        label_A15->setFont(font2);
        label_A15->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        groupBox = new QGroupBox(tab_2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(630, 70, 181, 341));
        groupBox->setFont(font2);
        labelHelp = new QLabel(groupBox);
        labelHelp->setObjectName(QStringLiteral("labelHelp"));
        labelHelp->setGeometry(QRect(10, 30, 151, 221));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(false);
        font3.setItalic(true);
        font3.setWeight(50);
        labelHelp->setFont(font3);
        labelHelp->setTextFormat(Qt::RichText);
        labelHelp->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        labelHelp->setWordWrap(true);
        label_C14 = new QLabel(tab_2);
        label_C14->setObjectName(QStringLiteral("label_C14"));
        label_C14->setGeometry(QRect(20, 420, 31, 16));
        label_C14->setFont(font2);
        label_C14->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B6 = new QLabel(tab_2);
        label_B6->setObjectName(QStringLiteral("label_B6"));
        label_B6->setGeometry(QRect(20, 320, 31, 16));
        label_B6->setFont(font2);
        label_B6->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A2 = new QLabel(tab_2);
        label_A2->setObjectName(QStringLiteral("label_A2"));
        label_A2->setGeometry(QRect(550, 240, 31, 16));
        label_A2->setFont(font2);
        label_A2->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B1 = new QLabel(tab_2);
        label_B1->setObjectName(QStringLiteral("label_B1"));
        label_B1->setGeometry(QRect(550, 100, 31, 16));
        label_B1->setFont(font2);
        label_B1->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B7 = new QLabel(tab_2);
        label_B7->setObjectName(QStringLiteral("label_B7"));
        label_B7->setGeometry(QRect(20, 340, 31, 16));
        label_B7->setFont(font2);
        label_B7->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A0 = new QLabel(tab_2);
        label_A0->setObjectName(QStringLiteral("label_A0"));
        label_A0->setGeometry(QRect(550, 280, 31, 16));
        label_A0->setFont(font2);
        label_A0->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A4 = new QLabel(tab_2);
        label_A4->setObjectName(QStringLiteral("label_A4"));
        label_A4->setGeometry(QRect(550, 200, 31, 16));
        label_A4->setFont(font2);
        label_A4->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A7 = new QLabel(tab_2);
        label_A7->setObjectName(QStringLiteral("label_A7"));
        label_A7->setGeometry(QRect(550, 140, 31, 16));
        label_A7->setFont(font2);
        label_A7->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B8 = new QLabel(tab_2);
        label_B8->setObjectName(QStringLiteral("label_B8"));
        label_B8->setGeometry(QRect(560, 350, 31, 16));
        label_B8->setFont(font2);
        label_B8->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A9 = new QLabel(tab_2);
        label_A9->setObjectName(QStringLiteral("label_A9"));
        label_A9->setGeometry(QRect(20, 160, 31, 16));
        label_A9->setFont(font2);
        label_A9->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B0 = new QLabel(tab_2);
        label_B0->setObjectName(QStringLiteral("label_B0"));
        label_B0->setGeometry(QRect(550, 120, 31, 16));
        label_B0->setFont(font2);
        label_B0->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label = new QLabel(tab_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(210, 20, 181, 411));
        label->setPixmap(QPixmap(QString::fromUtf8(":/Images/boardTypeII.jpg")));
        label->setScaledContents(true);
        label_C15 = new QLabel(tab_2);
        label_C15->setObjectName(QStringLiteral("label_C15"));
        label_C15->setGeometry(QRect(20, 400, 31, 16));
        label_C15->setFont(font2);
        label_C15->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A5 = new QLabel(tab_2);
        label_A5->setObjectName(QStringLiteral("label_A5"));
        label_A5->setGeometry(QRect(550, 180, 31, 16));
        label_A5->setFont(font2);
        label_A5->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B4 = new QLabel(tab_2);
        label_B4->setObjectName(QStringLiteral("label_B4"));
        label_B4->setGeometry(QRect(20, 280, 31, 16));
        label_B4->setFont(font2);
        label_B4->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B12 = new QLabel(tab_2);
        label_B12->setObjectName(QStringLiteral("label_B12"));
        label_B12->setGeometry(QRect(20, 60, 31, 16));
        label_B12->setFont(font2);
        label_B12->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A8 = new QLabel(tab_2);
        label_A8->setObjectName(QStringLiteral("label_A8"));
        label_A8->setGeometry(QRect(20, 140, 31, 16));
        label_A8->setFont(font2);
        label_A8->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B14 = new QLabel(tab_2);
        label_B14->setObjectName(QStringLiteral("label_B14"));
        label_B14->setGeometry(QRect(20, 100, 31, 16));
        label_B14->setFont(font2);
        label_B14->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A1 = new QLabel(tab_2);
        label_A1->setObjectName(QStringLiteral("label_A1"));
        label_A1->setGeometry(QRect(550, 260, 31, 16));
        label_A1->setFont(font2);
        label_A1->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B9 = new QLabel(tab_2);
        label_B9->setObjectName(QStringLiteral("label_B9"));
        label_B9->setGeometry(QRect(560, 330, 31, 16));
        label_B9->setFont(font2);
        label_B9->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A10 = new QLabel(tab_2);
        label_A10->setObjectName(QStringLiteral("label_A10"));
        label_A10->setGeometry(QRect(20, 180, 31, 16));
        label_A10->setFont(font2);
        label_A10->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A12 = new QLabel(tab_2);
        label_A12->setObjectName(QStringLiteral("label_A12"));
        label_A12->setGeometry(QRect(20, 220, 31, 16));
        label_A12->setFont(font2);
        label_A12->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_C13 = new QLabel(tab_2);
        label_C13->setObjectName(QStringLiteral("label_C13"));
        label_C13->setGeometry(QRect(550, 310, 31, 16));
        label_C13->setFont(font2);
        label_C13->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B10 = new QLabel(tab_2);
        label_B10->setObjectName(QStringLiteral("label_B10"));
        label_B10->setGeometry(QRect(550, 80, 31, 16));
        label_B10->setFont(font2);
        label_B10->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_3 = new QLabel(tab_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(630, 10, 91, 20));
        comboBox_BoardType = new QComboBox(tab_2);
        comboBox_BoardType->setObjectName(QStringLiteral("comboBox_BoardType"));
        comboBox_BoardType->setGeometry(QRect(630, 30, 141, 22));
        widget_PB25 = new oshpincombobox(tab_2);
        widget_PB25->setObjectName(QStringLiteral("widget_PB25"));
        widget_PB25->setGeometry(QRect(60, 60, 141, 21));
        widget_PB0 = new oshpincombobox(tab_2);
        widget_PB0->setObjectName(QStringLiteral("widget_PB0"));
        widget_PB0->setGeometry(QRect(400, 280, 141, 21));
        widget_PB1 = new oshpincombobox(tab_2);
        widget_PB1->setObjectName(QStringLiteral("widget_PB1"));
        widget_PB1->setGeometry(QRect(400, 260, 141, 21));
        widget_PB2 = new oshpincombobox(tab_2);
        widget_PB2->setObjectName(QStringLiteral("widget_PB2"));
        widget_PB2->setGeometry(QRect(400, 240, 141, 21));
        widget_PB3 = new oshpincombobox(tab_2);
        widget_PB3->setObjectName(QStringLiteral("widget_PB3"));
        widget_PB3->setGeometry(QRect(400, 220, 141, 21));
        widget_PB4 = new oshpincombobox(tab_2);
        widget_PB4->setObjectName(QStringLiteral("widget_PB4"));
        widget_PB4->setGeometry(QRect(400, 200, 141, 21));
        widget_PB5 = new oshpincombobox(tab_2);
        widget_PB5->setObjectName(QStringLiteral("widget_PB5"));
        widget_PB5->setGeometry(QRect(400, 180, 141, 21));
        widget_PB6 = new oshpincombobox(tab_2);
        widget_PB6->setObjectName(QStringLiteral("widget_PB6"));
        widget_PB6->setGeometry(QRect(400, 160, 141, 21));
        widget_PB7 = new oshpincombobox(tab_2);
        widget_PB7->setObjectName(QStringLiteral("widget_PB7"));
        widget_PB7->setGeometry(QRect(400, 140, 141, 21));
        widget_PB8 = new oshpincombobox(tab_2);
        widget_PB8->setObjectName(QStringLiteral("widget_PB8"));
        widget_PB8->setGeometry(QRect(60, 140, 141, 21));
        widget_PB9 = new oshpincombobox(tab_2);
        widget_PB9->setObjectName(QStringLiteral("widget_PB9"));
        widget_PB9->setGeometry(QRect(60, 160, 141, 21));
        widget_PB10 = new oshpincombobox(tab_2);
        widget_PB10->setObjectName(QStringLiteral("widget_PB10"));
        widget_PB10->setGeometry(QRect(60, 180, 141, 21));
        widget_PB11 = new oshpincombobox(tab_2);
        widget_PB11->setObjectName(QStringLiteral("widget_PB11"));
        widget_PB11->setGeometry(QRect(60, 200, 141, 21));
        widget_PB12 = new oshpincombobox(tab_2);
        widget_PB12->setObjectName(QStringLiteral("widget_PB12"));
        widget_PB12->setGeometry(QRect(60, 220, 141, 21));
        widget_PB13 = new oshpincombobox(tab_2);
        widget_PB13->setObjectName(QStringLiteral("widget_PB13"));
        widget_PB13->setGeometry(QRect(60, 240, 141, 21));
        widget_PB14 = new oshpincombobox(tab_2);
        widget_PB14->setObjectName(QStringLiteral("widget_PB14"));
        widget_PB14->setGeometry(QRect(400, 120, 141, 21));
        widget_PB15 = new oshpincombobox(tab_2);
        widget_PB15->setObjectName(QStringLiteral("widget_PB15"));
        widget_PB15->setGeometry(QRect(400, 100, 141, 21));
        widget_PB16 = new oshpincombobox(tab_2);
        widget_PB16->setObjectName(QStringLiteral("widget_PB16"));
        widget_PB16->setGeometry(QRect(60, 260, 141, 21));
        widget_PB17 = new oshpincombobox(tab_2);
        widget_PB17->setObjectName(QStringLiteral("widget_PB17"));
        widget_PB17->setGeometry(QRect(60, 280, 141, 21));
        widget_PB18 = new oshpincombobox(tab_2);
        widget_PB18->setObjectName(QStringLiteral("widget_PB18"));
        widget_PB18->setGeometry(QRect(60, 300, 141, 21));
        widget_PB19 = new oshpincombobox(tab_2);
        widget_PB19->setObjectName(QStringLiteral("widget_PB19"));
        widget_PB19->setGeometry(QRect(60, 320, 141, 21));
        widget_PB20 = new oshpincombobox(tab_2);
        widget_PB20->setObjectName(QStringLiteral("widget_PB20"));
        widget_PB20->setGeometry(QRect(60, 340, 141, 21));
        widget_PB21 = new oshpincombobox(tab_2);
        widget_PB21->setObjectName(QStringLiteral("widget_PB21"));
        widget_PB21->setGeometry(QRect(400, 350, 141, 21));
        widget_PB22 = new oshpincombobox(tab_2);
        widget_PB22->setObjectName(QStringLiteral("widget_PB22"));
        widget_PB22->setGeometry(QRect(400, 330, 141, 21));
        widget_PB23 = new oshpincombobox(tab_2);
        widget_PB23->setObjectName(QStringLiteral("widget_PB23"));
        widget_PB23->setGeometry(QRect(400, 80, 141, 21));
        widget_PB24 = new oshpincombobox(tab_2);
        widget_PB24->setObjectName(QStringLiteral("widget_PB24"));
        widget_PB24->setGeometry(QRect(400, 60, 141, 21));
        widget_PB26 = new oshpincombobox(tab_2);
        widget_PB26->setObjectName(QStringLiteral("widget_PB26"));
        widget_PB26->setGeometry(QRect(60, 80, 141, 21));
        widget_PB27 = new oshpincombobox(tab_2);
        widget_PB27->setObjectName(QStringLiteral("widget_PB27"));
        widget_PB27->setGeometry(QRect(60, 100, 141, 21));
        widget_PB28 = new oshpincombobox(tab_2);
        widget_PB28->setObjectName(QStringLiteral("widget_PB28"));
        widget_PB28->setGeometry(QRect(60, 120, 141, 21));
        widget_PB29 = new oshpincombobox(tab_2);
        widget_PB29->setObjectName(QStringLiteral("widget_PB29"));
        widget_PB29->setGeometry(QRect(400, 300, 141, 21));
        widget_PB30 = new oshpincombobox(tab_2);
        widget_PB30->setObjectName(QStringLiteral("widget_PB30"));
        widget_PB30->setGeometry(QRect(60, 420, 141, 21));
        widget_PB31 = new oshpincombobox(tab_2);
        widget_PB31->setObjectName(QStringLiteral("widget_PB31"));
        widget_PB31->setGeometry(QRect(60, 400, 141, 21));
        tabWidget->addTab(tab_2, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QStringLiteral("Pins Configuration"));
        label_B12->raise();
        label_B14->raise();
        label_A10->raise();
        label_A8->raise();
        label_B11->raise();
        label_A11->raise();
        label_A3->raise();
        label_B13->raise();
        label_A6->raise();
        label_B15->raise();
        label_B3->raise();
        label_B5->raise();
        label_A15->raise();
        groupBox->raise();
        label_C14->raise();
        label_B6->raise();
        label_A2->raise();
        label_B1->raise();
        label_B7->raise();
        label_A0->raise();
        label_A4->raise();
        label_A7->raise();
        label_B8->raise();
        label_A9->raise();
        label_B0->raise();
        label->raise();
        label_C15->raise();
        label_A5->raise();
        label_B4->raise();
        label_A1->raise();
        label_B9->raise();
        label_A12->raise();
        label_C13->raise();
        label_B10->raise();
        label_3->raise();
        comboBox_BoardType->raise();
        widget_PB25->raise();
        widget_PB0->raise();
        widget_PB1->raise();
        widget_PB2->raise();
        widget_PB3->raise();
        widget_PB4->raise();
        widget_PB5->raise();
        widget_PB6->raise();
        widget_PB7->raise();
        widget_PB8->raise();
        widget_PB9->raise();
        widget_PB10->raise();
        widget_PB11->raise();
        widget_PB12->raise();
        widget_PB13->raise();
        widget_PB14->raise();
        widget_PB15->raise();
        widget_PB16->raise();
        widget_PB17->raise();
        widget_PB18->raise();
        widget_PB19->raise();
        widget_PB20->raise();
        widget_PB21->raise();
        widget_PB22->raise();
        widget_PB23->raise();
        widget_PB24->raise();
        widget_PB26->raise();
        widget_PB27->raise();
        widget_PB28->raise();
        widget_PB29->raise();
        widget_PB30->raise();
        widget_PB31->raise();
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_48 = new QLabel(tab);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(20, 20, 47, 13));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        label_48->setFont(font4);
        label_49 = new QLabel(tab);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(20, 70, 47, 13));
        label_49->setFont(font4);
        label_50 = new QLabel(tab);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(20, 120, 47, 13));
        label_50->setFont(font4);
        label_51 = new QLabel(tab);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(20, 170, 47, 13));
        label_51->setFont(font4);
        label_52 = new QLabel(tab);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(20, 220, 47, 13));
        label_52->setFont(font4);
        label_53 = new QLabel(tab);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(20, 270, 47, 13));
        label_53->setFont(font4);
        checkBox_AxisComb = new QCheckBox(tab);
        checkBox_AxisComb->setObjectName(QStringLiteral("checkBox_AxisComb"));
        checkBox_AxisComb->setGeometry(QRect(20, 330, 111, 17));
        checkBox_AxisComb->setFont(font);
        comboBox_AxisCombBegin = new QComboBox(tab);
        comboBox_AxisCombBegin->setObjectName(QStringLiteral("comboBox_AxisCombBegin"));
        comboBox_AxisCombBegin->setGeometry(QRect(20, 360, 41, 22));
        comboBox_AxisCombEnd = new QComboBox(tab);
        comboBox_AxisCombEnd->setObjectName(QStringLiteral("comboBox_AxisCombEnd"));
        comboBox_AxisCombEnd->setGeometry(QRect(20, 410, 41, 22));
        horizontalSliderAxisComb = new QSlider(tab);
        horizontalSliderAxisComb->setObjectName(QStringLiteral("horizontalSliderAxisComb"));
        horizontalSliderAxisComb->setGeometry(QRect(210, 480, 391, 20));
        horizontalSliderAxisComb->setAutoFillBackground(false);
        horizontalSliderAxisComb->setMaximum(100);
        horizontalSliderAxisComb->setValue(50);
        horizontalSliderAxisComb->setOrientation(Qt::Horizontal);
        horizontalSliderAxisComb->setInvertedAppearance(false);
        horizontalSliderAxisComb->setInvertedControls(false);
        horizontalSliderAxisComb->setTickPosition(QSlider::TicksAbove);
        horizontalSliderAxisComb->setTickInterval(10);
        label_AxisComb1 = new QLabel(tab);
        label_AxisComb1->setObjectName(QStringLiteral("label_AxisComb1"));
        label_AxisComb1->setGeometry(QRect(235, 450, 31, 20));
        label_AxisComb2 = new QLabel(tab);
        label_AxisComb2->setObjectName(QStringLiteral("label_AxisComb2"));
        label_AxisComb2->setGeometry(QRect(455, 450, 31, 20));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(210, 450, 21, 20));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(265, 450, 101, 20));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(430, 450, 21, 20));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(485, 450, 111, 20));
        label_AxisCombPin1 = new QLabel(tab);
        label_AxisCombPin1->setObjectName(QStringLiteral("label_AxisCombPin1"));
        label_AxisCombPin1->setGeometry(QRect(370, 450, 21, 20));
        label_AxisCombPin2 = new QLabel(tab);
        label_AxisCombPin2->setObjectName(QStringLiteral("label_AxisCombPin2"));
        label_AxisCombPin2->setGeometry(QRect(590, 450, 21, 20));
        radioButtonCoopwoork = new QRadioButton(tab);
        radioButtonCoopwoork->setObjectName(QStringLiteral("radioButtonCoopwoork"));
        radioButtonCoopwoork->setGeometry(QRect(80, 460, 111, 17));
        radioButtonCoopwoork->setChecked(true);
        radioButtonEachonhisown = new QRadioButton(tab);
        radioButtonEachonhisown->setObjectName(QStringLiteral("radioButtonEachonhisown"));
        radioButtonEachonhisown->setGeometry(QRect(80, 480, 101, 17));
        widget_axis1 = new OSHaxiswca(tab);
        widget_axis1->setObjectName(QStringLiteral("widget_axis1"));
        widget_axis1->setGeometry(QRect(80, 10, 750, 43));
        widget_axis1->setMouseTracking(true);
        widget_axis2 = new OSHaxiswca(tab);
        widget_axis2->setObjectName(QStringLiteral("widget_axis2"));
        widget_axis2->setGeometry(QRect(80, 60, 750, 43));
        widget_axis2->setMouseTracking(true);
        widget_axis3 = new OSHaxiswca(tab);
        widget_axis3->setObjectName(QStringLiteral("widget_axis3"));
        widget_axis3->setGeometry(QRect(80, 110, 750, 43));
        widget_axis3->setMouseTracking(true);
        widget_axis4 = new OSHaxiswca(tab);
        widget_axis4->setObjectName(QStringLiteral("widget_axis4"));
        widget_axis4->setGeometry(QRect(80, 160, 750, 43));
        widget_axis4->setMouseTracking(true);
        widget_axis5 = new OSHaxiswca(tab);
        widget_axis5->setObjectName(QStringLiteral("widget_axis5"));
        widget_axis5->setGeometry(QRect(80, 210, 750, 43));
        widget_axis5->setMouseTracking(true);
        widget_axis6 = new OSHaxiswca(tab);
        widget_axis6->setObjectName(QStringLiteral("widget_axis6"));
        widget_axis6->setGeometry(QRect(80, 260, 750, 43));
        widget_axis6->setMouseTracking(true);
        widget_axisComb1 = new OSHaxiswca(tab);
        widget_axisComb1->setObjectName(QStringLiteral("widget_axisComb1"));
        widget_axisComb1->setGeometry(QRect(80, 350, 750, 43));
        widget_axisComb1->setMouseTracking(true);
        widget_axisComb2 = new OSHaxiswca(tab);
        widget_axisComb2->setObjectName(QStringLiteral("widget_axisComb2"));
        widget_axisComb2->setGeometry(QRect(80, 400, 750, 43));
        widget_axisComb2->setMouseTracking(true);
        tabWidget->addTab(tab, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QStringLiteral("Axes Config"));
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        widget_AS_big = new oshshapesw(tab_7);
        widget_AS_big->setObjectName(QStringLiteral("widget_AS_big"));
        widget_AS_big->setGeometry(QRect(52, 40, 561, 321));
        widget_AS_big->setMouseTracking(true);
        comboBox_curr_shape_prof = new QComboBox(tab_7);
        comboBox_curr_shape_prof->setObjectName(QStringLiteral("comboBox_curr_shape_prof"));
        comboBox_curr_shape_prof->setGeometry(QRect(120, 20, 161, 22));
        comboBox_curr_shape_prof->setEditable(true);
        comboBox_curr_shape_prof->setInsertPolicy(QComboBox::InsertAtCurrent);
        label_2 = new QLabel(tab_7);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 20, 81, 21));
        label_2->setFont(font);
        label_8 = new QLabel(tab_7);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(650, 50, 47, 13));
        comboBox_shape_axis_1 = new QComboBox(tab_7);
        comboBox_shape_axis_1->setObjectName(QStringLiteral("comboBox_shape_axis_1"));
        comboBox_shape_axis_1->setGeometry(QRect(650, 70, 161, 22));
        comboBox_shape_axis_1->setEditable(false);
        label_9 = new QLabel(tab_7);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(650, 100, 47, 13));
        comboBox_shape_axis_2 = new QComboBox(tab_7);
        comboBox_shape_axis_2->setObjectName(QStringLiteral("comboBox_shape_axis_2"));
        comboBox_shape_axis_2->setGeometry(QRect(650, 120, 161, 22));
        comboBox_shape_axis_2->setEditable(false);
        label_10 = new QLabel(tab_7);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(650, 150, 47, 13));
        comboBox_shape_axis_3 = new QComboBox(tab_7);
        comboBox_shape_axis_3->setObjectName(QStringLiteral("comboBox_shape_axis_3"));
        comboBox_shape_axis_3->setGeometry(QRect(650, 170, 161, 22));
        comboBox_shape_axis_3->setEditable(false);
        label_11 = new QLabel(tab_7);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(650, 200, 47, 13));
        comboBox_shape_axis_4 = new QComboBox(tab_7);
        comboBox_shape_axis_4->setObjectName(QStringLiteral("comboBox_shape_axis_4"));
        comboBox_shape_axis_4->setGeometry(QRect(650, 220, 161, 22));
        comboBox_shape_axis_4->setEditable(false);
        label_12 = new QLabel(tab_7);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(650, 250, 47, 13));
        comboBox_shape_axis_5 = new QComboBox(tab_7);
        comboBox_shape_axis_5->setObjectName(QStringLiteral("comboBox_shape_axis_5"));
        comboBox_shape_axis_5->setGeometry(QRect(650, 270, 161, 22));
        comboBox_shape_axis_5->setEditable(false);
        label_13 = new QLabel(tab_7);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(650, 300, 47, 13));
        comboBox_shape_axis_6 = new QComboBox(tab_7);
        comboBox_shape_axis_6->setObjectName(QStringLiteral("comboBox_shape_axis_6"));
        comboBox_shape_axis_6->setGeometry(QRect(650, 320, 161, 22));
        comboBox_shape_axis_6->setEditable(false);
        widget_AS_1 = new oshshapesw(tab_7);
        widget_AS_1->setObjectName(QStringLiteral("widget_AS_1"));
        widget_AS_1->setGeometry(QRect(30, 420, 120, 80));
        widget_AS_2 = new oshshapesw(tab_7);
        widget_AS_2->setObjectName(QStringLiteral("widget_AS_2"));
        widget_AS_2->setGeometry(QRect(160, 420, 120, 80));
        widget_AS_3 = new oshshapesw(tab_7);
        widget_AS_3->setObjectName(QStringLiteral("widget_AS_3"));
        widget_AS_3->setGeometry(QRect(290, 420, 120, 80));
        widget_AS_4 = new oshshapesw(tab_7);
        widget_AS_4->setObjectName(QStringLiteral("widget_AS_4"));
        widget_AS_4->setGeometry(QRect(420, 420, 120, 80));
        widget_AS_5 = new oshshapesw(tab_7);
        widget_AS_5->setObjectName(QStringLiteral("widget_AS_5"));
        widget_AS_5->setGeometry(QRect(550, 420, 120, 80));
        widget_AS_6 = new oshshapesw(tab_7);
        widget_AS_6->setObjectName(QStringLiteral("widget_AS_6"));
        widget_AS_6->setGeometry(QRect(680, 420, 120, 80));
        label_Prof_1 = new QLabel(tab_7);
        label_Prof_1->setObjectName(QStringLiteral("label_Prof_1"));
        label_Prof_1->setGeometry(QRect(70, 380, 47, 13));
        label_Prof_1->setAlignment(Qt::AlignCenter);
        label_Prof_2 = new QLabel(tab_7);
        label_Prof_2->setObjectName(QStringLiteral("label_Prof_2"));
        label_Prof_2->setGeometry(QRect(200, 380, 47, 13));
        label_Prof_2->setAlignment(Qt::AlignCenter);
        label_Prof_3 = new QLabel(tab_7);
        label_Prof_3->setObjectName(QStringLiteral("label_Prof_3"));
        label_Prof_3->setGeometry(QRect(330, 380, 47, 13));
        label_Prof_3->setAlignment(Qt::AlignCenter);
        label_Prof_4 = new QLabel(tab_7);
        label_Prof_4->setObjectName(QStringLiteral("label_Prof_4"));
        label_Prof_4->setGeometry(QRect(460, 380, 47, 13));
        label_Prof_4->setAlignment(Qt::AlignCenter);
        label_Prof_5 = new QLabel(tab_7);
        label_Prof_5->setObjectName(QStringLiteral("label_Prof_5"));
        label_Prof_5->setGeometry(QRect(590, 380, 47, 13));
        label_Prof_5->setAlignment(Qt::AlignCenter);
        label_Prof_6 = new QLabel(tab_7);
        label_Prof_6->setObjectName(QStringLiteral("label_Prof_6"));
        label_Prof_6->setGeometry(QRect(720, 380, 47, 13));
        label_Prof_6->setAlignment(Qt::AlignCenter);
        label_Prof_CustName_1 = new QLabel(tab_7);
        label_Prof_CustName_1->setObjectName(QStringLiteral("label_Prof_CustName_1"));
        label_Prof_CustName_1->setGeometry(QRect(45, 395, 91, 16));
        label_Prof_CustName_1->setAlignment(Qt::AlignCenter);
        label_Prof_CustName_2 = new QLabel(tab_7);
        label_Prof_CustName_2->setObjectName(QStringLiteral("label_Prof_CustName_2"));
        label_Prof_CustName_2->setGeometry(QRect(175, 395, 91, 16));
        label_Prof_CustName_2->setAlignment(Qt::AlignCenter);
        label_Prof_CustName_3 = new QLabel(tab_7);
        label_Prof_CustName_3->setObjectName(QStringLiteral("label_Prof_CustName_3"));
        label_Prof_CustName_3->setGeometry(QRect(305, 395, 91, 16));
        label_Prof_CustName_3->setAlignment(Qt::AlignCenter);
        label_Prof_CustName_4 = new QLabel(tab_7);
        label_Prof_CustName_4->setObjectName(QStringLiteral("label_Prof_CustName_4"));
        label_Prof_CustName_4->setGeometry(QRect(435, 395, 91, 16));
        label_Prof_CustName_4->setAlignment(Qt::AlignCenter);
        label_Prof_CustName_5 = new QLabel(tab_7);
        label_Prof_CustName_5->setObjectName(QStringLiteral("label_Prof_CustName_5"));
        label_Prof_CustName_5->setGeometry(QRect(565, 395, 91, 16));
        label_Prof_CustName_5->setAlignment(Qt::AlignCenter);
        label_Prof_CustName_6 = new QLabel(tab_7);
        label_Prof_CustName_6->setObjectName(QStringLiteral("label_Prof_CustName_6"));
        label_Prof_CustName_6->setGeometry(QRect(695, 395, 91, 16));
        label_Prof_CustName_6->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(tab_7);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(740, 30, 81, 16));
        label_14->setFont(font);
        tabWidget->addTab(tab_7, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QStringLiteral("Axes Shaping"));
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        label_POV1 = new QLabel(tab_3);
        label_POV1->setObjectName(QStringLiteral("label_POV1"));
        label_POV1->setEnabled(true);
        label_POV1->setGeometry(QRect(670, 20, 71, 71));
        label_POV1->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV1->setScaledContents(true);
        label_POV2 = new QLabel(tab_3);
        label_POV2->setObjectName(QStringLiteral("label_POV2"));
        label_POV2->setEnabled(true);
        label_POV2->setGeometry(QRect(760, 20, 71, 71));
        label_POV2->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV2->setScaledContents(true);
        label_POV3 = new QLabel(tab_3);
        label_POV3->setObjectName(QStringLiteral("label_POV3"));
        label_POV3->setEnabled(true);
        label_POV3->setGeometry(QRect(670, 110, 71, 71));
        label_POV3->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV3->setScaledContents(true);
        label_POV4 = new QLabel(tab_3);
        label_POV4->setObjectName(QStringLiteral("label_POV4"));
        label_POV4->setEnabled(true);
        label_POV4->setGeometry(QRect(760, 110, 71, 71));
        label_POV4->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV4->setScaledContents(true);
        widget_SB_1 = new oshbuttonw(tab_3);
        widget_SB_1->setObjectName(QStringLiteral("widget_SB_1"));
        widget_SB_1->setGeometry(QRect(20, 20, 51, 41));
        widget_SB_2 = new oshbuttonw(tab_3);
        widget_SB_2->setObjectName(QStringLiteral("widget_SB_2"));
        widget_SB_2->setGeometry(QRect(100, 20, 51, 41));
        widget_SB_3 = new oshbuttonw(tab_3);
        widget_SB_3->setObjectName(QStringLiteral("widget_SB_3"));
        widget_SB_3->setGeometry(QRect(180, 20, 51, 41));
        widget_SB_4 = new oshbuttonw(tab_3);
        widget_SB_4->setObjectName(QStringLiteral("widget_SB_4"));
        widget_SB_4->setGeometry(QRect(260, 20, 51, 41));
        widget_SB_5 = new oshbuttonw(tab_3);
        widget_SB_5->setObjectName(QStringLiteral("widget_SB_5"));
        widget_SB_5->setGeometry(QRect(340, 20, 51, 41));
        widget_SB_6 = new oshbuttonw(tab_3);
        widget_SB_6->setObjectName(QStringLiteral("widget_SB_6"));
        widget_SB_6->setGeometry(QRect(420, 20, 51, 41));
        widget_SB_7 = new oshbuttonw(tab_3);
        widget_SB_7->setObjectName(QStringLiteral("widget_SB_7"));
        widget_SB_7->setGeometry(QRect(500, 20, 51, 41));
        widget_SB_8 = new oshbuttonw(tab_3);
        widget_SB_8->setObjectName(QStringLiteral("widget_SB_8"));
        widget_SB_8->setGeometry(QRect(580, 20, 51, 41));
        widget_SB_9 = new oshbuttonw(tab_3);
        widget_SB_9->setObjectName(QStringLiteral("widget_SB_9"));
        widget_SB_9->setGeometry(QRect(20, 80, 51, 41));
        widget_SB_10 = new oshbuttonw(tab_3);
        widget_SB_10->setObjectName(QStringLiteral("widget_SB_10"));
        widget_SB_10->setGeometry(QRect(100, 80, 51, 41));
        widget_SB_11 = new oshbuttonw(tab_3);
        widget_SB_11->setObjectName(QStringLiteral("widget_SB_11"));
        widget_SB_11->setGeometry(QRect(180, 80, 51, 41));
        widget_SB_12 = new oshbuttonw(tab_3);
        widget_SB_12->setObjectName(QStringLiteral("widget_SB_12"));
        widget_SB_12->setGeometry(QRect(260, 80, 51, 41));
        widget_SB_13 = new oshbuttonw(tab_3);
        widget_SB_13->setObjectName(QStringLiteral("widget_SB_13"));
        widget_SB_13->setGeometry(QRect(340, 80, 51, 41));
        widget_SB_14 = new oshbuttonw(tab_3);
        widget_SB_14->setObjectName(QStringLiteral("widget_SB_14"));
        widget_SB_14->setGeometry(QRect(420, 80, 51, 41));
        widget_SB_15 = new oshbuttonw(tab_3);
        widget_SB_15->setObjectName(QStringLiteral("widget_SB_15"));
        widget_SB_15->setGeometry(QRect(500, 80, 51, 41));
        widget_SB_16 = new oshbuttonw(tab_3);
        widget_SB_16->setObjectName(QStringLiteral("widget_SB_16"));
        widget_SB_16->setGeometry(QRect(580, 80, 51, 41));
        widget_SB_17 = new oshbuttonw(tab_3);
        widget_SB_17->setObjectName(QStringLiteral("widget_SB_17"));
        widget_SB_17->setGeometry(QRect(20, 140, 51, 41));
        widget_SB_18 = new oshbuttonw(tab_3);
        widget_SB_18->setObjectName(QStringLiteral("widget_SB_18"));
        widget_SB_18->setGeometry(QRect(100, 140, 51, 41));
        widget_SB_19 = new oshbuttonw(tab_3);
        widget_SB_19->setObjectName(QStringLiteral("widget_SB_19"));
        widget_SB_19->setGeometry(QRect(180, 140, 51, 41));
        widget_SB_20 = new oshbuttonw(tab_3);
        widget_SB_20->setObjectName(QStringLiteral("widget_SB_20"));
        widget_SB_20->setGeometry(QRect(260, 140, 51, 41));
        widget_SB_21 = new oshbuttonw(tab_3);
        widget_SB_21->setObjectName(QStringLiteral("widget_SB_21"));
        widget_SB_21->setGeometry(QRect(340, 140, 51, 41));
        widget_SB_22 = new oshbuttonw(tab_3);
        widget_SB_22->setObjectName(QStringLiteral("widget_SB_22"));
        widget_SB_22->setGeometry(QRect(420, 140, 51, 41));
        widget_SB_23 = new oshbuttonw(tab_3);
        widget_SB_23->setObjectName(QStringLiteral("widget_SB_23"));
        widget_SB_23->setGeometry(QRect(500, 140, 51, 41));
        widget_SB_24 = new oshbuttonw(tab_3);
        widget_SB_24->setObjectName(QStringLiteral("widget_SB_24"));
        widget_SB_24->setGeometry(QRect(580, 140, 51, 41));
        widget_SB_25 = new oshbuttonw(tab_3);
        widget_SB_25->setObjectName(QStringLiteral("widget_SB_25"));
        widget_SB_25->setGeometry(QRect(20, 200, 51, 41));
        widget_SB_26 = new oshbuttonw(tab_3);
        widget_SB_26->setObjectName(QStringLiteral("widget_SB_26"));
        widget_SB_26->setGeometry(QRect(100, 200, 51, 41));
        widget_SB_27 = new oshbuttonw(tab_3);
        widget_SB_27->setObjectName(QStringLiteral("widget_SB_27"));
        widget_SB_27->setGeometry(QRect(180, 200, 51, 41));
        widget_SB_28 = new oshbuttonw(tab_3);
        widget_SB_28->setObjectName(QStringLiteral("widget_SB_28"));
        widget_SB_28->setGeometry(QRect(260, 200, 51, 41));
        widget_SB_29 = new oshbuttonw(tab_3);
        widget_SB_29->setObjectName(QStringLiteral("widget_SB_29"));
        widget_SB_29->setGeometry(QRect(340, 200, 51, 41));
        widget_SB_30 = new oshbuttonw(tab_3);
        widget_SB_30->setObjectName(QStringLiteral("widget_SB_30"));
        widget_SB_30->setGeometry(QRect(420, 200, 51, 41));
        widget_SB_31 = new oshbuttonw(tab_3);
        widget_SB_31->setObjectName(QStringLiteral("widget_SB_31"));
        widget_SB_31->setGeometry(QRect(500, 200, 51, 41));
        widget_SB_32 = new oshbuttonw(tab_3);
        widget_SB_32->setObjectName(QStringLiteral("widget_SB_32"));
        widget_SB_32->setGeometry(QRect(580, 200, 51, 41));
        widget_SB_33 = new oshbuttonw(tab_3);
        widget_SB_33->setObjectName(QStringLiteral("widget_SB_33"));
        widget_SB_33->setGeometry(QRect(20, 260, 51, 41));
        widget_SB_34 = new oshbuttonw(tab_3);
        widget_SB_34->setObjectName(QStringLiteral("widget_SB_34"));
        widget_SB_34->setGeometry(QRect(100, 260, 51, 41));
        widget_SB_35 = new oshbuttonw(tab_3);
        widget_SB_35->setObjectName(QStringLiteral("widget_SB_35"));
        widget_SB_35->setGeometry(QRect(180, 260, 51, 41));
        widget_SB_36 = new oshbuttonw(tab_3);
        widget_SB_36->setObjectName(QStringLiteral("widget_SB_36"));
        widget_SB_36->setGeometry(QRect(260, 260, 51, 41));
        widget_SB_37 = new oshbuttonw(tab_3);
        widget_SB_37->setObjectName(QStringLiteral("widget_SB_37"));
        widget_SB_37->setGeometry(QRect(340, 260, 51, 41));
        widget_SB_38 = new oshbuttonw(tab_3);
        widget_SB_38->setObjectName(QStringLiteral("widget_SB_38"));
        widget_SB_38->setGeometry(QRect(420, 260, 51, 41));
        widget_SB_39 = new oshbuttonw(tab_3);
        widget_SB_39->setObjectName(QStringLiteral("widget_SB_39"));
        widget_SB_39->setGeometry(QRect(500, 260, 51, 41));
        widget_SB_40 = new oshbuttonw(tab_3);
        widget_SB_40->setObjectName(QStringLiteral("widget_SB_40"));
        widget_SB_40->setGeometry(QRect(580, 260, 51, 41));
        widget_SB_41 = new oshbuttonw(tab_3);
        widget_SB_41->setObjectName(QStringLiteral("widget_SB_41"));
        widget_SB_41->setGeometry(QRect(20, 320, 51, 41));
        widget_SB_42 = new oshbuttonw(tab_3);
        widget_SB_42->setObjectName(QStringLiteral("widget_SB_42"));
        widget_SB_42->setGeometry(QRect(100, 320, 51, 41));
        widget_SB_43 = new oshbuttonw(tab_3);
        widget_SB_43->setObjectName(QStringLiteral("widget_SB_43"));
        widget_SB_43->setGeometry(QRect(180, 320, 51, 41));
        widget_SB_44 = new oshbuttonw(tab_3);
        widget_SB_44->setObjectName(QStringLiteral("widget_SB_44"));
        widget_SB_44->setGeometry(QRect(260, 320, 51, 41));
        widget_SB_45 = new oshbuttonw(tab_3);
        widget_SB_45->setObjectName(QStringLiteral("widget_SB_45"));
        widget_SB_45->setGeometry(QRect(340, 320, 51, 41));
        widget_SB_46 = new oshbuttonw(tab_3);
        widget_SB_46->setObjectName(QStringLiteral("widget_SB_46"));
        widget_SB_46->setGeometry(QRect(420, 320, 51, 41));
        widget_SB_47 = new oshbuttonw(tab_3);
        widget_SB_47->setObjectName(QStringLiteral("widget_SB_47"));
        widget_SB_47->setGeometry(QRect(500, 320, 51, 41));
        widget_SB_48 = new oshbuttonw(tab_3);
        widget_SB_48->setObjectName(QStringLiteral("widget_SB_48"));
        widget_SB_48->setGeometry(QRect(580, 320, 51, 41));
        widget_SB_49 = new oshbuttonw(tab_3);
        widget_SB_49->setObjectName(QStringLiteral("widget_SB_49"));
        widget_SB_49->setGeometry(QRect(20, 380, 51, 41));
        widget_SB_50 = new oshbuttonw(tab_3);
        widget_SB_50->setObjectName(QStringLiteral("widget_SB_50"));
        widget_SB_50->setGeometry(QRect(100, 380, 51, 41));
        widget_SB_51 = new oshbuttonw(tab_3);
        widget_SB_51->setObjectName(QStringLiteral("widget_SB_51"));
        widget_SB_51->setGeometry(QRect(180, 380, 51, 41));
        widget_SB_52 = new oshbuttonw(tab_3);
        widget_SB_52->setObjectName(QStringLiteral("widget_SB_52"));
        widget_SB_52->setGeometry(QRect(260, 380, 51, 41));
        widget_SB_53 = new oshbuttonw(tab_3);
        widget_SB_53->setObjectName(QStringLiteral("widget_SB_53"));
        widget_SB_53->setGeometry(QRect(340, 380, 51, 41));
        widget_SB_54 = new oshbuttonw(tab_3);
        widget_SB_54->setObjectName(QStringLiteral("widget_SB_54"));
        widget_SB_54->setGeometry(QRect(420, 380, 51, 41));
        widget_SB_55 = new oshbuttonw(tab_3);
        widget_SB_55->setObjectName(QStringLiteral("widget_SB_55"));
        widget_SB_55->setGeometry(QRect(500, 380, 51, 41));
        widget_SB_56 = new oshbuttonw(tab_3);
        widget_SB_56->setObjectName(QStringLiteral("widget_SB_56"));
        widget_SB_56->setGeometry(QRect(580, 380, 51, 41));
        widget_SB_57 = new oshbuttonw(tab_3);
        widget_SB_57->setObjectName(QStringLiteral("widget_SB_57"));
        widget_SB_57->setGeometry(QRect(20, 440, 51, 41));
        widget_SB_58 = new oshbuttonw(tab_3);
        widget_SB_58->setObjectName(QStringLiteral("widget_SB_58"));
        widget_SB_58->setGeometry(QRect(100, 440, 51, 41));
        widget_SB_59 = new oshbuttonw(tab_3);
        widget_SB_59->setObjectName(QStringLiteral("widget_SB_59"));
        widget_SB_59->setGeometry(QRect(180, 440, 51, 41));
        widget_SB_60 = new oshbuttonw(tab_3);
        widget_SB_60->setObjectName(QStringLiteral("widget_SB_60"));
        widget_SB_60->setGeometry(QRect(260, 440, 51, 41));
        widget_SB_61 = new oshbuttonw(tab_3);
        widget_SB_61->setObjectName(QStringLiteral("widget_SB_61"));
        widget_SB_61->setGeometry(QRect(340, 440, 51, 41));
        widget_SB_62 = new oshbuttonw(tab_3);
        widget_SB_62->setObjectName(QStringLiteral("widget_SB_62"));
        widget_SB_62->setGeometry(QRect(420, 440, 51, 41));
        widget_SB_63 = new oshbuttonw(tab_3);
        widget_SB_63->setObjectName(QStringLiteral("widget_SB_63"));
        widget_SB_63->setGeometry(QRect(500, 440, 51, 41));
        widget_SB_64 = new oshbuttonw(tab_3);
        widget_SB_64->setObjectName(QStringLiteral("widget_SB_64"));
        widget_SB_64->setGeometry(QRect(580, 440, 51, 41));
        groupBox_2 = new QGroupBox(tab_3);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(660, 210, 181, 271));
        groupBox_2->setFont(font2);
        labelHelp_SB = new QLabel(groupBox_2);
        labelHelp_SB->setObjectName(QStringLiteral("labelHelp_SB"));
        labelHelp_SB->setGeometry(QRect(10, 30, 151, 221));
        labelHelp_SB->setFont(font3);
        labelHelp_SB->setTextFormat(Qt::RichText);
        labelHelp_SB->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        labelHelp_SB->setWordWrap(true);
        label_POV1name = new QLabel(tab_3);
        label_POV1name->setObjectName(QStringLiteral("label_POV1name"));
        label_POV1name->setGeometry(QRect(670, 0, 31, 16));
        label_POV2name = new QLabel(tab_3);
        label_POV2name->setObjectName(QStringLiteral("label_POV2name"));
        label_POV2name->setGeometry(QRect(760, 0, 31, 16));
        label_POV3name = new QLabel(tab_3);
        label_POV3name->setObjectName(QStringLiteral("label_POV3name"));
        label_POV3name->setGeometry(QRect(670, 90, 31, 16));
        label_POV4name = new QLabel(tab_3);
        label_POV4name->setObjectName(QStringLiteral("label_POV4name"));
        label_POV4name->setGeometry(QRect(760, 90, 31, 16));
        tabWidget->addTab(tab_3, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QStringLiteral("Buttons"));
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_ZeroA2B = new QLabel(tab_6);
        label_ZeroA2B->setObjectName(QStringLiteral("label_ZeroA2B"));
        label_ZeroA2B->setGeometry(QRect(40, 20, 431, 41));
        widget_A2B_1 = new osha2bw(tab_6);
        widget_A2B_1->setObjectName(QStringLiteral("widget_A2B_1"));
        widget_A2B_1->setGeometry(QRect(20, 10, 751, 41));
        widget_A2B_1->setMouseTracking(true);
        widget_A2B_2 = new osha2bw(tab_6);
        widget_A2B_2->setObjectName(QStringLiteral("widget_A2B_2"));
        widget_A2B_2->setGeometry(QRect(20, 60, 751, 41));
        widget_A2B_2->setMouseTracking(true);
        widget_A2B_3 = new osha2bw(tab_6);
        widget_A2B_3->setObjectName(QStringLiteral("widget_A2B_3"));
        widget_A2B_3->setGeometry(QRect(20, 110, 751, 41));
        widget_A2B_3->setMouseTracking(true);
        widget_A2B_4 = new osha2bw(tab_6);
        widget_A2B_4->setObjectName(QStringLiteral("widget_A2B_4"));
        widget_A2B_4->setGeometry(QRect(20, 160, 751, 41));
        widget_A2B_4->setMouseTracking(true);
        widget_A2B_5 = new osha2bw(tab_6);
        widget_A2B_5->setObjectName(QStringLiteral("widget_A2B_5"));
        widget_A2B_5->setGeometry(QRect(20, 210, 751, 41));
        widget_A2B_5->setMouseTracking(true);
        widget_A2B_6 = new osha2bw(tab_6);
        widget_A2B_6->setObjectName(QStringLiteral("widget_A2B_6"));
        widget_A2B_6->setGeometry(QRect(20, 260, 751, 41));
        widget_A2B_6->setMouseTracking(true);
        widget_A2B_7 = new osha2bw(tab_6);
        widget_A2B_7->setObjectName(QStringLiteral("widget_A2B_7"));
        widget_A2B_7->setGeometry(QRect(20, 310, 751, 41));
        widget_A2B_7->setMouseTracking(true);
        widget_A2B_8 = new osha2bw(tab_6);
        widget_A2B_8->setObjectName(QStringLiteral("widget_A2B_8"));
        widget_A2B_8->setGeometry(QRect(20, 360, 751, 41));
        widget_A2B_8->setMouseTracking(true);
        widget_A2B_9 = new osha2bw(tab_6);
        widget_A2B_9->setObjectName(QStringLiteral("widget_A2B_9"));
        widget_A2B_9->setGeometry(QRect(20, 410, 751, 41));
        widget_A2B_9->setMouseTracking(true);
        widget_A2B_10 = new osha2bw(tab_6);
        widget_A2B_10->setObjectName(QStringLiteral("widget_A2B_10"));
        widget_A2B_10->setGeometry(QRect(20, 460, 751, 41));
        widget_A2B_10->setMouseTracking(true);
        tabWidget->addTab(tab_6, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QStringLiteral("Analog 2 Buttons"));
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_ZeroSglEncoders = new QLabel(tab_5);
        label_ZeroSglEncoders->setObjectName(QStringLiteral("label_ZeroSglEncoders"));
        label_ZeroSglEncoders->setGeometry(QRect(60, 30, 391, 41));
        label_SEHelp = new QLabel(tab_5);
        label_SEHelp->setObjectName(QStringLiteral("label_SEHelp"));
        label_SEHelp->setGeometry(QRect(550, 10, 271, 91));
        label_SEHelp->setWordWrap(true);
        widget_SE1 = new oshsingenc(tab_5);
        widget_SE1->setObjectName(QStringLiteral("widget_SE1"));
        widget_SE1->setGeometry(QRect(10, 10, 201, 91));
        widget_SE2 = new oshsingenc(tab_5);
        widget_SE2->setObjectName(QStringLiteral("widget_SE2"));
        widget_SE2->setGeometry(QRect(260, 10, 201, 91));
        widget_SE3 = new oshsingenc(tab_5);
        widget_SE3->setObjectName(QStringLiteral("widget_SE3"));
        widget_SE3->setGeometry(QRect(10, 110, 201, 91));
        widget_SE4 = new oshsingenc(tab_5);
        widget_SE4->setObjectName(QStringLiteral("widget_SE4"));
        widget_SE4->setGeometry(QRect(260, 110, 201, 91));
        widget_SE5 = new oshsingenc(tab_5);
        widget_SE5->setObjectName(QStringLiteral("widget_SE5"));
        widget_SE5->setGeometry(QRect(10, 210, 201, 91));
        widget_SE6 = new oshsingenc(tab_5);
        widget_SE6->setObjectName(QStringLiteral("widget_SE6"));
        widget_SE6->setGeometry(QRect(260, 210, 201, 91));
        widget_SE7 = new oshsingenc(tab_5);
        widget_SE7->setObjectName(QStringLiteral("widget_SE7"));
        widget_SE7->setGeometry(QRect(10, 310, 201, 91));
        widget_SE8 = new oshsingenc(tab_5);
        widget_SE8->setObjectName(QStringLiteral("widget_SE8"));
        widget_SE8->setGeometry(QRect(260, 310, 201, 91));
        widget_SE9 = new oshsingenc(tab_5);
        widget_SE9->setObjectName(QStringLiteral("widget_SE9"));
        widget_SE9->setGeometry(QRect(10, 410, 201, 91));
        widget_SE10 = new oshsingenc(tab_5);
        widget_SE10->setObjectName(QStringLiteral("widget_SE10"));
        widget_SE10->setGeometry(QRect(260, 410, 201, 91));
        widget_SE11 = new oshsingenc(tab_5);
        widget_SE11->setObjectName(QStringLiteral("widget_SE11"));
        widget_SE11->setGeometry(QRect(510, 110, 201, 91));
        widget_SE12 = new oshsingenc(tab_5);
        widget_SE12->setObjectName(QStringLiteral("widget_SE12"));
        widget_SE12->setGeometry(QRect(510, 210, 201, 91));
        widget_SE13 = new oshsingenc(tab_5);
        widget_SE13->setObjectName(QStringLiteral("widget_SE13"));
        widget_SE13->setGeometry(QRect(510, 310, 201, 91));
        widget_SE14 = new oshsingenc(tab_5);
        widget_SE14->setObjectName(QStringLiteral("widget_SE14"));
        widget_SE14->setGeometry(QRect(510, 410, 201, 91));
        tabWidget->addTab(tab_5, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QStringLiteral("Single Encoders"));
        widget_SE2->raise();
        label_SEHelp->raise();
        widget_SE1->raise();
        label_ZeroSglEncoders->raise();
        widget_SE3->raise();
        widget_SE4->raise();
        widget_SE5->raise();
        widget_SE6->raise();
        widget_SE7->raise();
        widget_SE8->raise();
        widget_SE9->raise();
        widget_SE10->raise();
        widget_SE11->raise();
        widget_SE12->raise();
        widget_SE13->raise();
        widget_SE14->raise();
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_54 = new QLabel(tab_4);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(140, 260, 491, 16));
        label_55 = new QLabel(tab_4);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(140, 400, 341, 16));
        label_56 = new QLabel(tab_4);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(140, 430, 281, 16));
        label_57 = new QLabel(tab_4);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(140, 230, 491, 16));
        spinBox__Rot_Press_time = new QSpinBox(tab_4);
        spinBox__Rot_Press_time->setObjectName(QStringLiteral("spinBox__Rot_Press_time"));
        spinBox__Rot_Press_time->setGeometry(QRect(60, 230, 61, 21));
        spinBox__Rot_Press_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox__Rot_Press_time->setMaximum(65535);
        spinBox_RotSwitch_Press_time = new QSpinBox(tab_4);
        spinBox_RotSwitch_Press_time->setObjectName(QStringLiteral("spinBox_RotSwitch_Press_time"));
        spinBox_RotSwitch_Press_time->setGeometry(QRect(60, 260, 61, 21));
        spinBox_RotSwitch_Press_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_RotSwitch_Press_time->setMaximum(65535);
        spinBox_Rot_Debounce_time = new QSpinBox(tab_4);
        spinBox_Rot_Debounce_time->setObjectName(QStringLiteral("spinBox_Rot_Debounce_time"));
        spinBox_Rot_Debounce_time->setGeometry(QRect(60, 400, 61, 21));
        spinBox_Rot_Debounce_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_Rot_Debounce_time->setMaximum(65535);
        spinBox_Button_Debounce_time = new QSpinBox(tab_4);
        spinBox_Button_Debounce_time->setObjectName(QStringLiteral("spinBox_Button_Debounce_time"));
        spinBox_Button_Debounce_time->setGeometry(QRect(60, 430, 61, 21));
        spinBox_Button_Debounce_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_Button_Debounce_time->setMaximum(65535);
        line = new QFrame(tab_4);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 180, 811, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        spinBox_USB_exchange = new QSpinBox(tab_4);
        spinBox_USB_exchange->setObjectName(QStringLiteral("spinBox_USB_exchange"));
        spinBox_USB_exchange->setGeometry(QRect(60, 90, 61, 21));
        spinBox_USB_exchange->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_USB_exchange->setMinimum(1);
        spinBox_USB_exchange->setMaximum(255);
        label_59 = new QLabel(tab_4);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(140, 90, 441, 16));
        lineEdit_Device_ident = new QLineEdit(tab_4);
        lineEdit_Device_ident->setObjectName(QStringLiteral("lineEdit_Device_ident"));
        lineEdit_Device_ident->setGeometry(QRect(52, 60, 71, 20));
        lineEdit_Device_ident->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        lineEdit_Device_ident->setMaxLength(10);
        label_60 = new QLabel(tab_4);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(140, 60, 521, 16));
        spinBox_RotSwitch_min_time = new QSpinBox(tab_4);
        spinBox_RotSwitch_min_time->setObjectName(QStringLiteral("spinBox_RotSwitch_min_time"));
        spinBox_RotSwitch_min_time->setGeometry(QRect(60, 330, 61, 21));
        spinBox_RotSwitch_min_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_RotSwitch_min_time->setMaximum(65535);
        label_61 = new QLabel(tab_4);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(140, 330, 491, 16));
        spinBox_A2B_Press_time = new QSpinBox(tab_4);
        spinBox_A2B_Press_time->setObjectName(QStringLiteral("spinBox_A2B_Press_time"));
        spinBox_A2B_Press_time->setGeometry(QRect(60, 290, 61, 21));
        spinBox_A2B_Press_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_A2B_Press_time->setMaximum(65535);
        label_62 = new QLabel(tab_4);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(140, 290, 491, 16));
        spinBox_A2B_min_time = new QSpinBox(tab_4);
        spinBox_A2B_min_time->setObjectName(QStringLiteral("spinBox_A2B_min_time"));
        spinBox_A2B_min_time->setGeometry(QRect(60, 360, 61, 21));
        spinBox_A2B_min_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_A2B_min_time->setMaximum(65535);
        label_63 = new QLabel(tab_4);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(140, 360, 491, 16));
        tabWidget->addTab(tab_4, QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QStringLiteral("Tuning"));
        saveConfig_Button = new QPushButton(centralWidget);
        saveConfig_Button->setObjectName(QStringLiteral("saveConfig_Button"));
        saveConfig_Button->setGeometry(QRect(10, 200, 151, 41));
        saveConfig_Button->setFont(font);
        saveFile_Button = new QPushButton(centralWidget);
        saveFile_Button->setObjectName(QStringLiteral("saveFile_Button"));
        saveFile_Button->setGeometry(QRect(10, 470, 151, 41));
        saveFile_Button->setFont(font);
        loadFile_Button = new QPushButton(centralWidget);
        loadFile_Button->setObjectName(QStringLiteral("loadFile_Button"));
        loadFile_Button->setGeometry(QRect(10, 420, 151, 41));
        loadFile_Button->setFont(font);
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(880, 0, 101, 20));
        resetConfig_button = new QPushButton(centralWidget);
        resetConfig_button->setObjectName(QStringLiteral("resetConfig_button"));
        resetConfig_button->setGeometry(QRect(10, 310, 151, 41));
        resetConfig_button->setFont(font);
        restoreConfig_button = new QPushButton(centralWidget);
        restoreConfig_button->setObjectName(QStringLiteral("restoreConfig_button"));
        restoreConfig_button->setGeometry(QRect(10, 360, 151, 41));
        restoreConfig_button->setFont(font);
        label_Stud_version = new QLabel(centralWidget);
        label_Stud_version->setObjectName(QStringLiteral("label_Stud_version"));
        label_Stud_version->setGeometry(QRect(980, 0, 31, 21));
        label_58 = new QLabel(centralWidget);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(890, 20, 91, 21));
        label_Firmware_Vers = new QLabel(centralWidget);
        label_Firmware_Vers->setObjectName(QStringLiteral("label_Firmware_Vers"));
        label_Firmware_Vers->setGeometry(QRect(980, 20, 31, 21));
        startLog_Button = new QPushButton(centralWidget);
        startLog_Button->setObjectName(QStringLiteral("startLog_Button"));
        startLog_Button->setGeometry(QRect(10, 530, 151, 41));
        startLog_Button->setFont(font);
        startLog_Button->setCheckable(true);
        OSHStudio->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(OSHStudio);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        QFont font5;
        font5.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font5.setPointSize(8);
        font5.setItalic(true);
        statusBar->setFont(font5);
        statusBar->setLayoutDirection(Qt::LeftToRight);
        OSHStudio->setStatusBar(statusBar);

        retranslateUi(OSHStudio);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(OSHStudio);
    } // setupUi

    void retranslateUi(QMainWindow *OSHStudio)
    {
        OSHStudio->setWindowTitle(QApplication::translate("OSHStudio", "OSHStudio", nullptr));
        getConfig_button->setText(QApplication::translate("OSHStudio", "Get Config from Device", nullptr));
        label_35->setText(QApplication::translate("OSHStudio", "Connected Devices:", nullptr));
        label_DevDescImg->setText(QString());
        label_DevDesc->setText(QApplication::translate("OSHStudio", "OpenSimHardware Pedals & Buttons Controller                               (OSH PB Controller)", nullptr));
        label_B11->setText(QApplication::translate("OSHStudio", "B11", nullptr));
        label_A11->setText(QApplication::translate("OSHStudio", "A11", nullptr));
        label_A3->setText(QApplication::translate("OSHStudio", "A3", nullptr));
        label_B13->setText(QApplication::translate("OSHStudio", "B13", nullptr));
        label_A6->setText(QApplication::translate("OSHStudio", "A6", nullptr));
        label_B15->setText(QApplication::translate("OSHStudio", "B15", nullptr));
        label_B3->setText(QApplication::translate("OSHStudio", "B3", nullptr));
        label_B5->setText(QApplication::translate("OSHStudio", "B5", nullptr));
        label_A15->setText(QApplication::translate("OSHStudio", "A15", nullptr));
        groupBox->setTitle(QApplication::translate("OSHStudio", "Current Configuration", nullptr));
        labelHelp->setText(QString());
        label_C14->setText(QApplication::translate("OSHStudio", "C14", nullptr));
        label_B6->setText(QApplication::translate("OSHStudio", "B6", nullptr));
        label_A2->setText(QApplication::translate("OSHStudio", "A2", nullptr));
        label_B1->setText(QApplication::translate("OSHStudio", "B1", nullptr));
        label_B7->setText(QApplication::translate("OSHStudio", "B7", nullptr));
        label_A0->setText(QApplication::translate("OSHStudio", "A0", nullptr));
        label_A4->setText(QApplication::translate("OSHStudio", "A4", nullptr));
        label_A7->setText(QApplication::translate("OSHStudio", "A7", nullptr));
        label_B8->setText(QApplication::translate("OSHStudio", "B8", nullptr));
        label_A9->setText(QApplication::translate("OSHStudio", "A9", nullptr));
        label_B0->setText(QApplication::translate("OSHStudio", "B0", nullptr));
        label->setText(QString());
        label_C15->setText(QApplication::translate("OSHStudio", "C15", nullptr));
        label_A5->setText(QApplication::translate("OSHStudio", "A5", nullptr));
        label_B4->setText(QApplication::translate("OSHStudio", "B4", nullptr));
        label_B12->setText(QApplication::translate("OSHStudio", "B12", nullptr));
        label_A8->setText(QApplication::translate("OSHStudio", "A8", nullptr));
        label_B14->setText(QApplication::translate("OSHStudio", "B14", nullptr));
        label_A1->setText(QApplication::translate("OSHStudio", "A1", nullptr));
        label_B9->setText(QApplication::translate("OSHStudio", "B9", nullptr));
        label_A10->setText(QApplication::translate("OSHStudio", "A10", nullptr));
        label_A12->setText(QApplication::translate("OSHStudio", "A12", nullptr));
        label_C13->setText(QApplication::translate("OSHStudio", "C13", nullptr));
        label_B10->setText(QApplication::translate("OSHStudio", "B10", nullptr));
        label_3->setText(QApplication::translate("OSHStudio", "Your board type:", nullptr));
        label_48->setText(QApplication::translate("OSHStudio", "AXIS1", nullptr));
        label_49->setText(QApplication::translate("OSHStudio", "AXIS2", nullptr));
        label_50->setText(QApplication::translate("OSHStudio", "AXIS3", nullptr));
        label_51->setText(QApplication::translate("OSHStudio", "AXIS4", nullptr));
        label_52->setText(QApplication::translate("OSHStudio", "AXIS5", nullptr));
        label_53->setText(QApplication::translate("OSHStudio", "AXIS6", nullptr));
        checkBox_AxisComb->setText(QApplication::translate("OSHStudio", "Combined Axis", nullptr));
        label_AxisComb1->setText(QString());
        label_AxisComb2->setText(QString());
        label_4->setText(QApplication::translate("OSHStudio", "The", nullptr));
        label_5->setText(QApplication::translate("OSHStudio", "of AXIS6 will be from", nullptr));
        label_6->setText(QApplication::translate("OSHStudio", "The", nullptr));
        label_7->setText(QApplication::translate("OSHStudio", "of AXIS6 will be from", nullptr));
        label_AxisCombPin1->setText(QString());
        label_AxisCombPin2->setText(QString());
        radioButtonCoopwoork->setText(QApplication::translate("OSHStudio", "Cooperative work", nullptr));
        radioButtonEachonhisown->setText(QApplication::translate("OSHStudio", "Each on his own", nullptr));
        label_2->setText(QApplication::translate("OSHStudio", "Current Profile", nullptr));
        label_8->setText(QApplication::translate("OSHStudio", "AXIS 1", nullptr));
        label_9->setText(QApplication::translate("OSHStudio", "AXIS 2", nullptr));
        label_10->setText(QApplication::translate("OSHStudio", "AXIS 3", nullptr));
        label_11->setText(QApplication::translate("OSHStudio", "AXIS 4", nullptr));
        label_12->setText(QApplication::translate("OSHStudio", "AXIS 5", nullptr));
        label_13->setText(QApplication::translate("OSHStudio", "AXIS 6", nullptr));
        label_Prof_1->setText(QApplication::translate("OSHStudio", "Profile 1", nullptr));
        label_Prof_2->setText(QApplication::translate("OSHStudio", "Profile 2", nullptr));
        label_Prof_3->setText(QApplication::translate("OSHStudio", "Profile 3", nullptr));
        label_Prof_4->setText(QApplication::translate("OSHStudio", "Profile 4", nullptr));
        label_Prof_5->setText(QApplication::translate("OSHStudio", "Profile 5", nullptr));
        label_Prof_6->setText(QApplication::translate("OSHStudio", "Profile 6", nullptr));
        label_Prof_CustName_1->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_Prof_CustName_2->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_Prof_CustName_3->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_Prof_CustName_4->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_Prof_CustName_5->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_Prof_CustName_6->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_14->setText(QApplication::translate("OSHStudio", "Assignment", nullptr));
        label_POV1->setText(QString());
        label_POV2->setText(QString());
        label_POV3->setText(QString());
        label_POV4->setText(QString());
        groupBox_2->setTitle(QApplication::translate("OSHStudio", "Buttons Configuration", nullptr));
        labelHelp_SB->setText(QString());
        label_POV1name->setText(QApplication::translate("OSHStudio", "POV1", nullptr));
        label_POV2name->setText(QApplication::translate("OSHStudio", "POV2", nullptr));
        label_POV3name->setText(QApplication::translate("OSHStudio", "POV3", nullptr));
        label_POV4name->setText(QApplication::translate("OSHStudio", "POV4", nullptr));
        label_ZeroA2B->setText(QApplication::translate("OSHStudio", "You don't have configured any of analog to buttons inputs in \"Pins Configuration\" Tab. ", nullptr));
        label_ZeroSglEncoders->setText(QApplication::translate("OSHStudio", "You don't have configured any of single encoders in \"Pins Configuration\" Tab. ", nullptr));
        label_SEHelp->setText(QApplication::translate("OSHStudio", "You can configure pins for your single encoders here. Red colour means some conflict - different pin types of one encoder or shared pin between two encoders.", nullptr));
        label_54->setText(QApplication::translate("OSHStudio", "Amount of time a button will be pressed when Rotary Switch position changed, ms", nullptr));
        label_55->setText(QApplication::translate("OSHStudio", "Debounce time for Rotary Encoders, ms", nullptr));
        label_56->setText(QApplication::translate("OSHStudio", "Debounce time for Buttons, ms", nullptr));
        label_57->setText(QApplication::translate("OSHStudio", "Amount of time a button will be pressed when Rotary Encoders position changed, ms", nullptr));
        label_59->setText(QApplication::translate("OSHStudio", "USB polling interval, ms. It means USB exchange frequency of", nullptr));
        label_60->setText(QApplication::translate("OSHStudio", "Your identifier for the device, it will appear in Windows as \"OSH PB Controller\"", nullptr));
        label_61->setText(QApplication::translate("OSHStudio", "Time since previous Rotary Switch position change, if less then button press is not registered, ms", nullptr));
        label_62->setText(QApplication::translate("OSHStudio", "Amount of time a button will be pressed when Analog Input position changed, ms", nullptr));
        label_63->setText(QApplication::translate("OSHStudio", "Time since previous Analog Input position change, if less then button press is not registered, ms", nullptr));
        saveConfig_Button->setText(QApplication::translate("OSHStudio", "Save Config to Device", nullptr));
        saveFile_Button->setText(QApplication::translate("OSHStudio", "Save Config to File", nullptr));
        loadFile_Button->setText(QApplication::translate("OSHStudio", "Load Config from File", nullptr));
        label_34->setText(QApplication::translate("OSHStudio", "OSH Studio version:", nullptr));
        resetConfig_button->setText(QApplication::translate("OSHStudio", "Reset All Pins", nullptr));
        restoreConfig_button->setText(QApplication::translate("OSHStudio", "Restore Default Config", nullptr));
        label_Stud_version->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_58->setText(QApplication::translate("OSHStudio", "Firmware version:", nullptr));
        label_Firmware_Vers->setText(QString());
        startLog_Button->setText(QApplication::translate("OSHStudio", "Start Logging to File", nullptr));
    } // retranslateUi

};

namespace Ui {
    class OSHStudio: public Ui_OSHStudio {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_OSHSTUDIO_H
