/********************************************************************************
** Form generated from reading UI file 'oshstudio.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_OSHSTUDIO_H
#define UI_OSHSTUDIO_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include "oshaxiswca.h"
#include "oshpincombobox.h"

QT_BEGIN_NAMESPACE

class Ui_OSHStudio
{
public:
    QWidget *centralWidget;
    QPushButton *getConfig_button;
    QLabel *label_35;
    QLabel *label_DevDescImg;
    QLabel *label_DevDesc;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QLabel *label_B11;
    QLabel *label_A11;
    QLabel *label_A3;
    QLabel *label_B13;
    QLabel *label_A6;
    QLabel *label_B15;
    QLabel *label_B3;
    QLabel *label_B5;
    QLabel *label_A15;
    QGroupBox *groupBox;
    QLabel *labelHelp;
    QLabel *label_C14;
    QLabel *label_B6;
    QLabel *label_A2;
    QLabel *label_B1;
    QLabel *label_B7;
    QLabel *label_A0;
    QLabel *label_A4;
    QLabel *label_A7;
    QLabel *label_B8;
    QLabel *label_A9;
    QLabel *label_B0;
    QLabel *label;
    QLabel *label_C15;
    QLabel *label_A5;
    QLabel *label_B4;
    QLabel *label_B12;
    QLabel *label_A8;
    QLabel *label_B14;
    QLabel *label_A1;
    QLabel *label_B9;
    QLabel *label_A10;
    QLabel *label_A12;
    QLabel *label_C13;
    QLabel *label_B10;
    QLabel *label_3;
    QComboBox *comboBox_BoardType;
    oshpincombobox *widget_PB25;
    oshpincombobox *widget_PB0;
    oshpincombobox *widget_PB1;
    oshpincombobox *widget_PB2;
    oshpincombobox *widget_PB3;
    oshpincombobox *widget_PB4;
    oshpincombobox *widget_PB5;
    oshpincombobox *widget_PB6;
    oshpincombobox *widget_PB7;
    oshpincombobox *widget_PB8;
    oshpincombobox *widget_PB9;
    oshpincombobox *widget_PB10;
    oshpincombobox *widget_PB11;
    oshpincombobox *widget_PB12;
    oshpincombobox *widget_PB13;
    oshpincombobox *widget_PB14;
    oshpincombobox *widget_PB15;
    oshpincombobox *widget_PB16;
    oshpincombobox *widget_PB17;
    oshpincombobox *widget_PB18;
    oshpincombobox *widget_PB19;
    oshpincombobox *widget_PB20;
    oshpincombobox *widget_PB21;
    oshpincombobox *widget_PB22;
    oshpincombobox *widget_PB23;
    oshpincombobox *widget_PB24;
    oshpincombobox *widget_PB26;
    oshpincombobox *widget_PB27;
    oshpincombobox *widget_PB28;
    oshpincombobox *widget_PB29;
    oshpincombobox *widget_PB30;
    oshpincombobox *widget_PB31;
    QWidget *tab;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QCheckBox *checkBox_AxisComb;
    QComboBox *comboBox_AxisCombBegin;
    QComboBox *comboBox_AxisCombEnd;
    QSlider *horizontalSliderAxisComb;
    QLabel *label_AxisComb1;
    QLabel *label_AxisComb2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_AxisCombPin1;
    QLabel *label_AxisCombPin2;
    QRadioButton *radioButtonCoopwoork;
    QRadioButton *radioButtonEachonhisown;
    OSHaxiswca *widget_axis1;
    OSHaxiswca *widget_axis2;
    OSHaxiswca *widget_axis3;
    OSHaxiswca *widget_axis4;
    OSHaxiswca *widget_axis5;
    OSHaxiswca *widget_axis6;
    OSHaxiswca *widget_axisComb1;
    OSHaxiswca *widget_axisComb2;
    QWidget *tab_3;
    QLabel *labelButt_16;
    QLabel *labelButt_1;
    QLabel *labelButt_2;
    QLabel *labelButt_3;
    QLabel *labelButt_4;
    QLabel *labelButt_5;
    QLabel *labelButt_6;
    QLabel *labelButt_7;
    QLabel *labelButt_24;
    QLabel *labelButt_9;
    QLabel *labelButt_10;
    QLabel *labelButt_11;
    QLabel *labelButt_12;
    QLabel *labelButt_13;
    QLabel *labelButt_14;
    QLabel *labelButt_15;
    QLabel *labelButt_32;
    QLabel *labelButt_17;
    QLabel *labelButt_18;
    QLabel *labelButt_19;
    QLabel *labelButt_20;
    QLabel *labelButt_21;
    QLabel *labelButt_22;
    QLabel *labelButt_23;
    QLabel *labelButt_40;
    QLabel *labelButt_25;
    QLabel *labelButt_26;
    QLabel *labelButt_27;
    QLabel *labelButt_28;
    QLabel *labelButt_29;
    QLabel *labelButt_30;
    QLabel *labelButt_31;
    QLabel *labelButt_48;
    QLabel *labelButt_33;
    QLabel *labelButt_34;
    QLabel *labelButt_35;
    QLabel *labelButt_36;
    QLabel *labelButt_37;
    QLabel *labelButt_38;
    QLabel *labelButt_39;
    QLabel *labelButt_56;
    QLabel *labelButt_41;
    QLabel *labelButt_42;
    QLabel *labelButt_43;
    QLabel *labelButt_44;
    QLabel *labelButt_45;
    QLabel *labelButt_46;
    QLabel *labelButt_47;
    QLabel *labelButt_8;
    QLabel *labelButt_0;
    QLabel *labelButt_49;
    QLabel *labelButt_57;
    QLabel *labelButt_50;
    QLabel *labelButt_58;
    QLabel *labelButt_51;
    QLabel *labelButt_59;
    QLabel *labelButt_52;
    QLabel *labelButt_60;
    QLabel *labelButt_53;
    QLabel *labelButt_61;
    QLabel *labelButt_54;
    QLabel *labelButt_62;
    QLabel *labelButt_55;
    QLabel *labelButt_63;
    QLabel *label_117;
    QLabel *label_POV1;
    QLabel *label_POV2;
    QLabel *label_POV3;
    QLabel *label_POV4;
    QCheckBox *checkBox_POV1;
    QCheckBox *checkBox_POV2;
    QCheckBox *checkBox_POV3;
    QCheckBox *checkBox_POV4;
    QLabel *label_8;
    QSlider *horiSlider_A2B;
    QLabel *label_9;
    QLabel *label_10;
    QWidget *tab_5;
    QLabel *label_SE1;
    QComboBox *comboBox_SEA1;
    QComboBox *comboBox_SEB1;
    QLabel *label_SE1_CPin;
    QLabel *label_SE2;
    QComboBox *comboBox_SEA2;
    QLabel *label_SE2_CPin;
    QComboBox *comboBox_SEB2;
    QLabel *label_SE3;
    QComboBox *comboBox_SEA3;
    QLabel *label_SE3_CPin;
    QComboBox *comboBox_SEB3;
    QLabel *label_SE4;
    QComboBox *comboBox_SEA4;
    QComboBox *comboBox_SEB4;
    QLabel *label_SE4_CPin;
    QLabel *label_SE6_CPin;
    QComboBox *comboBox_SEA5;
    QLabel *label_SE5_CPin;
    QComboBox *comboBox_SEA7;
    QLabel *label_SE8;
    QComboBox *comboBox_SEB5;
    QComboBox *comboBox_SEB6;
    QLabel *label_SE7_CPin;
    QLabel *label_SE8_CPin;
    QComboBox *comboBox_SEB7;
    QLabel *label_SE6;
    QComboBox *comboBox_SEA8;
    QComboBox *comboBox_SEA6;
    QComboBox *comboBox_SEB8;
    QLabel *label_SE7;
    QLabel *label_SE5;
    QLabel *label_SE10_CPin;
    QComboBox *comboBox_SEA9;
    QLabel *label_SE9_CPin;
    QComboBox *comboBox_SEA11;
    QLabel *label_SE12;
    QComboBox *comboBox_SEB9;
    QComboBox *comboBox_SEB10;
    QLabel *label_SE11_CPin;
    QLabel *label_SE12_CPin;
    QComboBox *comboBox_SEB11;
    QLabel *label_SE10;
    QComboBox *comboBox_SEA12;
    QComboBox *comboBox_SEA10;
    QComboBox *comboBox_SEB12;
    QLabel *label_SE11;
    QLabel *label_SE9;
    QLabel *label_SE14_CPin;
    QComboBox *comboBox_SEA13;
    QLabel *label_SE13_CPin;
    QComboBox *comboBox_SEB13;
    QComboBox *comboBox_SEB14;
    QLabel *label_SE14;
    QComboBox *comboBox_SEA14;
    QLabel *label_SE13;
    QLabel *label_ZeroSglEncoders;
    QLabel *label_2;
    QWidget *tab_4;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QSpinBox *spinBox__Rot_Press_time;
    QSpinBox *spinBox_RotSwitch_Press_time;
    QSpinBox *spinBox_Rot_Debounce_time;
    QSpinBox *spinBox_Button_Debounce_time;
    QFrame *line;
    QSpinBox *spinBox_USB_exchange;
    QLabel *label_59;
    QLineEdit *lineEdit_Device_ident;
    QLabel *label_60;
    QWidget *tab_6;
    oshpincombobox *widget;
    oshpincombobox *widget_2;
    oshpincombobox *widget_3;
    QComboBox *comboBox;
    QPushButton *saveConfig_Button;
    QPushButton *saveFile_Button;
    QPushButton *loadFile_Button;
    QLabel *label_34;
    QPushButton *resetConfig_button;
    QPushButton *restoreConfig_button;
    QLabel *label_Stud_version;
    QLabel *label_58;
    QLabel *label_Firmware_Vers;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *OSHStudio)
    {
        if (OSHStudio->objectName().isEmpty())
            OSHStudio->setObjectName(QStringLiteral("OSHStudio"));
        OSHStudio->resize(1026, 590);
        QIcon icon;
        icon.addFile(QStringLiteral(":/Images/openhardware.ico"), QSize(), QIcon::Normal, QIcon::Off);
        OSHStudio->setWindowIcon(icon);
        centralWidget = new QWidget(OSHStudio);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        getConfig_button = new QPushButton(centralWidget);
        getConfig_button->setObjectName(QStringLiteral("getConfig_button"));
        getConfig_button->setGeometry(QRect(10, 150, 151, 41));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        getConfig_button->setFont(font);
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 10, 141, 21));
        label_35->setFont(font);
        label_DevDescImg = new QLabel(centralWidget);
        label_DevDescImg->setObjectName(QStringLiteral("label_DevDescImg"));
        label_DevDescImg->setEnabled(true);
        label_DevDescImg->setGeometry(QRect(-10, 30, 71, 51));
        label_DevDescImg->setStyleSheet(QStringLiteral("image: url(:/Images/cropped-OK-big-green-button.png);"));
        label_DevDesc = new QLabel(centralWidget);
        label_DevDesc->setObjectName(QStringLiteral("label_DevDesc"));
        label_DevDesc->setEnabled(true);
        label_DevDesc->setGeometry(QRect(40, 30, 121, 51));
        label_DevDesc->setAlignment(Qt::AlignCenter);
        label_DevDesc->setWordWrap(true);
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(170, 30, 851, 541));
        QFont font1;
        font1.setPointSize(8);
        font1.setBold(true);
        font1.setWeight(75);
        tabWidget->setFont(font1);
        tabWidget->setLayoutDirection(Qt::LeftToRight);
        tabWidget->setAutoFillBackground(false);
        tabWidget->setStyleSheet(QStringLiteral("background-color: rgb(240, 240, 240);"));
        tabWidget->setTabPosition(QTabWidget::North);
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        label_B11 = new QLabel(tab_2);
        label_B11->setObjectName(QStringLiteral("label_B11"));
        label_B11->setGeometry(QRect(550, 60, 31, 16));
        QFont font2;
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        label_B11->setFont(font2);
        label_B11->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A11 = new QLabel(tab_2);
        label_A11->setObjectName(QStringLiteral("label_A11"));
        label_A11->setGeometry(QRect(20, 200, 31, 16));
        label_A11->setFont(font2);
        label_A11->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A3 = new QLabel(tab_2);
        label_A3->setObjectName(QStringLiteral("label_A3"));
        label_A3->setGeometry(QRect(550, 220, 31, 16));
        label_A3->setFont(font2);
        label_A3->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B13 = new QLabel(tab_2);
        label_B13->setObjectName(QStringLiteral("label_B13"));
        label_B13->setGeometry(QRect(20, 80, 31, 16));
        label_B13->setFont(font2);
        label_B13->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A6 = new QLabel(tab_2);
        label_A6->setObjectName(QStringLiteral("label_A6"));
        label_A6->setGeometry(QRect(550, 160, 31, 16));
        label_A6->setFont(font2);
        label_A6->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B15 = new QLabel(tab_2);
        label_B15->setObjectName(QStringLiteral("label_B15"));
        label_B15->setGeometry(QRect(20, 120, 31, 16));
        label_B15->setFont(font2);
        label_B15->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B3 = new QLabel(tab_2);
        label_B3->setObjectName(QStringLiteral("label_B3"));
        label_B3->setGeometry(QRect(20, 260, 31, 16));
        label_B3->setFont(font2);
        label_B3->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B5 = new QLabel(tab_2);
        label_B5->setObjectName(QStringLiteral("label_B5"));
        label_B5->setGeometry(QRect(20, 300, 31, 16));
        label_B5->setFont(font2);
        label_B5->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A15 = new QLabel(tab_2);
        label_A15->setObjectName(QStringLiteral("label_A15"));
        label_A15->setGeometry(QRect(20, 240, 31, 16));
        label_A15->setFont(font2);
        label_A15->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        groupBox = new QGroupBox(tab_2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(630, 70, 181, 341));
        groupBox->setFont(font2);
        labelHelp = new QLabel(groupBox);
        labelHelp->setObjectName(QStringLiteral("labelHelp"));
        labelHelp->setGeometry(QRect(10, 30, 151, 221));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(false);
        font3.setItalic(true);
        font3.setWeight(50);
        labelHelp->setFont(font3);
        labelHelp->setTextFormat(Qt::RichText);
        labelHelp->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        labelHelp->setWordWrap(true);
        label_C14 = new QLabel(tab_2);
        label_C14->setObjectName(QStringLiteral("label_C14"));
        label_C14->setGeometry(QRect(20, 420, 31, 16));
        label_C14->setFont(font2);
        label_C14->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B6 = new QLabel(tab_2);
        label_B6->setObjectName(QStringLiteral("label_B6"));
        label_B6->setGeometry(QRect(20, 320, 31, 16));
        label_B6->setFont(font2);
        label_B6->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A2 = new QLabel(tab_2);
        label_A2->setObjectName(QStringLiteral("label_A2"));
        label_A2->setGeometry(QRect(550, 240, 31, 16));
        label_A2->setFont(font2);
        label_A2->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B1 = new QLabel(tab_2);
        label_B1->setObjectName(QStringLiteral("label_B1"));
        label_B1->setGeometry(QRect(550, 100, 31, 16));
        label_B1->setFont(font2);
        label_B1->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B7 = new QLabel(tab_2);
        label_B7->setObjectName(QStringLiteral("label_B7"));
        label_B7->setGeometry(QRect(20, 340, 31, 16));
        label_B7->setFont(font2);
        label_B7->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A0 = new QLabel(tab_2);
        label_A0->setObjectName(QStringLiteral("label_A0"));
        label_A0->setGeometry(QRect(550, 280, 31, 16));
        label_A0->setFont(font2);
        label_A0->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A4 = new QLabel(tab_2);
        label_A4->setObjectName(QStringLiteral("label_A4"));
        label_A4->setGeometry(QRect(550, 200, 31, 16));
        label_A4->setFont(font2);
        label_A4->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A7 = new QLabel(tab_2);
        label_A7->setObjectName(QStringLiteral("label_A7"));
        label_A7->setGeometry(QRect(550, 140, 31, 16));
        label_A7->setFont(font2);
        label_A7->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B8 = new QLabel(tab_2);
        label_B8->setObjectName(QStringLiteral("label_B8"));
        label_B8->setGeometry(QRect(560, 350, 31, 16));
        label_B8->setFont(font2);
        label_B8->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A9 = new QLabel(tab_2);
        label_A9->setObjectName(QStringLiteral("label_A9"));
        label_A9->setGeometry(QRect(20, 160, 31, 16));
        label_A9->setFont(font2);
        label_A9->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B0 = new QLabel(tab_2);
        label_B0->setObjectName(QStringLiteral("label_B0"));
        label_B0->setGeometry(QRect(550, 120, 31, 16));
        label_B0->setFont(font2);
        label_B0->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label = new QLabel(tab_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(210, 20, 181, 411));
        label->setPixmap(QPixmap(QString::fromUtf8(":/Images/boardTypeII.jpg")));
        label->setScaledContents(true);
        label_C15 = new QLabel(tab_2);
        label_C15->setObjectName(QStringLiteral("label_C15"));
        label_C15->setGeometry(QRect(20, 400, 31, 16));
        label_C15->setFont(font2);
        label_C15->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_A5 = new QLabel(tab_2);
        label_A5->setObjectName(QStringLiteral("label_A5"));
        label_A5->setGeometry(QRect(550, 180, 31, 16));
        label_A5->setFont(font2);
        label_A5->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B4 = new QLabel(tab_2);
        label_B4->setObjectName(QStringLiteral("label_B4"));
        label_B4->setGeometry(QRect(20, 280, 31, 16));
        label_B4->setFont(font2);
        label_B4->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B12 = new QLabel(tab_2);
        label_B12->setObjectName(QStringLiteral("label_B12"));
        label_B12->setGeometry(QRect(20, 60, 31, 16));
        label_B12->setFont(font2);
        label_B12->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A8 = new QLabel(tab_2);
        label_A8->setObjectName(QStringLiteral("label_A8"));
        label_A8->setGeometry(QRect(20, 140, 31, 16));
        label_A8->setFont(font2);
        label_A8->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_B14 = new QLabel(tab_2);
        label_B14->setObjectName(QStringLiteral("label_B14"));
        label_B14->setGeometry(QRect(20, 100, 31, 16));
        label_B14->setFont(font2);
        label_B14->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A1 = new QLabel(tab_2);
        label_A1->setObjectName(QStringLiteral("label_A1"));
        label_A1->setGeometry(QRect(550, 260, 31, 16));
        label_A1->setFont(font2);
        label_A1->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B9 = new QLabel(tab_2);
        label_B9->setObjectName(QStringLiteral("label_B9"));
        label_B9->setGeometry(QRect(560, 330, 31, 16));
        label_B9->setFont(font2);
        label_B9->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A10 = new QLabel(tab_2);
        label_A10->setObjectName(QStringLiteral("label_A10"));
        label_A10->setGeometry(QRect(20, 180, 31, 16));
        label_A10->setFont(font2);
        label_A10->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_A12 = new QLabel(tab_2);
        label_A12->setObjectName(QStringLiteral("label_A12"));
        label_A12->setGeometry(QRect(20, 220, 31, 16));
        label_A12->setFont(font2);
        label_A12->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_C13 = new QLabel(tab_2);
        label_C13->setObjectName(QStringLiteral("label_C13"));
        label_C13->setGeometry(QRect(550, 310, 31, 16));
        label_C13->setFont(font2);
        label_C13->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_B10 = new QLabel(tab_2);
        label_B10->setObjectName(QStringLiteral("label_B10"));
        label_B10->setGeometry(QRect(550, 80, 31, 16));
        label_B10->setFont(font2);
        label_B10->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_3 = new QLabel(tab_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(630, 10, 91, 20));
        comboBox_BoardType = new QComboBox(tab_2);
        comboBox_BoardType->setObjectName(QStringLiteral("comboBox_BoardType"));
        comboBox_BoardType->setGeometry(QRect(630, 30, 141, 22));
        widget_PB25 = new oshpincombobox(tab_2);
        widget_PB25->setObjectName(QStringLiteral("widget_PB25"));
        widget_PB25->setGeometry(QRect(60, 60, 141, 21));
        widget_PB0 = new oshpincombobox(tab_2);
        widget_PB0->setObjectName(QStringLiteral("widget_PB0"));
        widget_PB0->setGeometry(QRect(400, 280, 141, 21));
        widget_PB1 = new oshpincombobox(tab_2);
        widget_PB1->setObjectName(QStringLiteral("widget_PB1"));
        widget_PB1->setGeometry(QRect(400, 260, 141, 21));
        widget_PB2 = new oshpincombobox(tab_2);
        widget_PB2->setObjectName(QStringLiteral("widget_PB2"));
        widget_PB2->setGeometry(QRect(400, 240, 141, 21));
        widget_PB3 = new oshpincombobox(tab_2);
        widget_PB3->setObjectName(QStringLiteral("widget_PB3"));
        widget_PB3->setGeometry(QRect(400, 220, 141, 21));
        widget_PB4 = new oshpincombobox(tab_2);
        widget_PB4->setObjectName(QStringLiteral("widget_PB4"));
        widget_PB4->setGeometry(QRect(400, 200, 141, 21));
        widget_PB5 = new oshpincombobox(tab_2);
        widget_PB5->setObjectName(QStringLiteral("widget_PB5"));
        widget_PB5->setGeometry(QRect(400, 180, 141, 21));
        widget_PB6 = new oshpincombobox(tab_2);
        widget_PB6->setObjectName(QStringLiteral("widget_PB6"));
        widget_PB6->setGeometry(QRect(400, 160, 141, 21));
        widget_PB7 = new oshpincombobox(tab_2);
        widget_PB7->setObjectName(QStringLiteral("widget_PB7"));
        widget_PB7->setGeometry(QRect(400, 140, 141, 21));
        widget_PB8 = new oshpincombobox(tab_2);
        widget_PB8->setObjectName(QStringLiteral("widget_PB8"));
        widget_PB8->setGeometry(QRect(60, 140, 141, 21));
        widget_PB9 = new oshpincombobox(tab_2);
        widget_PB9->setObjectName(QStringLiteral("widget_PB9"));
        widget_PB9->setGeometry(QRect(60, 160, 141, 21));
        widget_PB10 = new oshpincombobox(tab_2);
        widget_PB10->setObjectName(QStringLiteral("widget_PB10"));
        widget_PB10->setGeometry(QRect(60, 180, 141, 21));
        widget_PB11 = new oshpincombobox(tab_2);
        widget_PB11->setObjectName(QStringLiteral("widget_PB11"));
        widget_PB11->setGeometry(QRect(60, 200, 141, 21));
        widget_PB12 = new oshpincombobox(tab_2);
        widget_PB12->setObjectName(QStringLiteral("widget_PB12"));
        widget_PB12->setGeometry(QRect(60, 220, 141, 21));
        widget_PB13 = new oshpincombobox(tab_2);
        widget_PB13->setObjectName(QStringLiteral("widget_PB13"));
        widget_PB13->setGeometry(QRect(60, 240, 141, 21));
        widget_PB14 = new oshpincombobox(tab_2);
        widget_PB14->setObjectName(QStringLiteral("widget_PB14"));
        widget_PB14->setGeometry(QRect(400, 120, 141, 21));
        widget_PB15 = new oshpincombobox(tab_2);
        widget_PB15->setObjectName(QStringLiteral("widget_PB15"));
        widget_PB15->setGeometry(QRect(400, 100, 141, 21));
        widget_PB16 = new oshpincombobox(tab_2);
        widget_PB16->setObjectName(QStringLiteral("widget_PB16"));
        widget_PB16->setGeometry(QRect(60, 260, 141, 21));
        widget_PB17 = new oshpincombobox(tab_2);
        widget_PB17->setObjectName(QStringLiteral("widget_PB17"));
        widget_PB17->setGeometry(QRect(60, 280, 141, 21));
        widget_PB18 = new oshpincombobox(tab_2);
        widget_PB18->setObjectName(QStringLiteral("widget_PB18"));
        widget_PB18->setGeometry(QRect(60, 300, 141, 21));
        widget_PB19 = new oshpincombobox(tab_2);
        widget_PB19->setObjectName(QStringLiteral("widget_PB19"));
        widget_PB19->setGeometry(QRect(60, 320, 141, 21));
        widget_PB20 = new oshpincombobox(tab_2);
        widget_PB20->setObjectName(QStringLiteral("widget_PB20"));
        widget_PB20->setGeometry(QRect(60, 340, 141, 21));
        widget_PB21 = new oshpincombobox(tab_2);
        widget_PB21->setObjectName(QStringLiteral("widget_PB21"));
        widget_PB21->setGeometry(QRect(400, 350, 141, 21));
        widget_PB22 = new oshpincombobox(tab_2);
        widget_PB22->setObjectName(QStringLiteral("widget_PB22"));
        widget_PB22->setGeometry(QRect(400, 330, 141, 21));
        widget_PB23 = new oshpincombobox(tab_2);
        widget_PB23->setObjectName(QStringLiteral("widget_PB23"));
        widget_PB23->setGeometry(QRect(400, 80, 141, 21));
        widget_PB24 = new oshpincombobox(tab_2);
        widget_PB24->setObjectName(QStringLiteral("widget_PB24"));
        widget_PB24->setGeometry(QRect(400, 60, 141, 21));
        widget_PB26 = new oshpincombobox(tab_2);
        widget_PB26->setObjectName(QStringLiteral("widget_PB26"));
        widget_PB26->setGeometry(QRect(60, 80, 141, 21));
        widget_PB27 = new oshpincombobox(tab_2);
        widget_PB27->setObjectName(QStringLiteral("widget_PB27"));
        widget_PB27->setGeometry(QRect(60, 100, 141, 21));
        widget_PB28 = new oshpincombobox(tab_2);
        widget_PB28->setObjectName(QStringLiteral("widget_PB28"));
        widget_PB28->setGeometry(QRect(60, 120, 141, 21));
        widget_PB29 = new oshpincombobox(tab_2);
        widget_PB29->setObjectName(QStringLiteral("widget_PB29"));
        widget_PB29->setGeometry(QRect(400, 300, 141, 21));
        widget_PB30 = new oshpincombobox(tab_2);
        widget_PB30->setObjectName(QStringLiteral("widget_PB30"));
        widget_PB30->setGeometry(QRect(60, 420, 141, 21));
        widget_PB31 = new oshpincombobox(tab_2);
        widget_PB31->setObjectName(QStringLiteral("widget_PB31"));
        widget_PB31->setGeometry(QRect(60, 400, 141, 21));
        tabWidget->addTab(tab_2, QString());
        label_B12->raise();
        label_B14->raise();
        label_A10->raise();
        label_A8->raise();
        label_B11->raise();
        label_A11->raise();
        label_A3->raise();
        label_B13->raise();
        label_A6->raise();
        label_B15->raise();
        label_B3->raise();
        label_B5->raise();
        label_A15->raise();
        groupBox->raise();
        label_C14->raise();
        label_B6->raise();
        label_A2->raise();
        label_B1->raise();
        label_B7->raise();
        label_A0->raise();
        label_A4->raise();
        label_A7->raise();
        label_B8->raise();
        label_A9->raise();
        label_B0->raise();
        label->raise();
        label_C15->raise();
        label_A5->raise();
        label_B4->raise();
        label_A1->raise();
        label_B9->raise();
        label_A12->raise();
        label_C13->raise();
        label_B10->raise();
        label_3->raise();
        comboBox_BoardType->raise();
        widget_PB25->raise();
        widget_PB0->raise();
        widget_PB1->raise();
        widget_PB2->raise();
        widget_PB3->raise();
        widget_PB4->raise();
        widget_PB5->raise();
        widget_PB6->raise();
        widget_PB7->raise();
        widget_PB8->raise();
        widget_PB9->raise();
        widget_PB10->raise();
        widget_PB11->raise();
        widget_PB12->raise();
        widget_PB13->raise();
        widget_PB14->raise();
        widget_PB15->raise();
        widget_PB16->raise();
        widget_PB17->raise();
        widget_PB18->raise();
        widget_PB19->raise();
        widget_PB20->raise();
        widget_PB21->raise();
        widget_PB22->raise();
        widget_PB23->raise();
        widget_PB24->raise();
        widget_PB26->raise();
        widget_PB27->raise();
        widget_PB28->raise();
        widget_PB29->raise();
        widget_PB30->raise();
        widget_PB31->raise();
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_48 = new QLabel(tab);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(20, 20, 47, 13));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        label_48->setFont(font4);
        label_49 = new QLabel(tab);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(20, 70, 47, 13));
        label_49->setFont(font4);
        label_50 = new QLabel(tab);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(20, 120, 47, 13));
        label_50->setFont(font4);
        label_51 = new QLabel(tab);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(20, 170, 47, 13));
        label_51->setFont(font4);
        label_52 = new QLabel(tab);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(20, 220, 47, 13));
        label_52->setFont(font4);
        label_53 = new QLabel(tab);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(20, 270, 47, 13));
        label_53->setFont(font4);
        checkBox_AxisComb = new QCheckBox(tab);
        checkBox_AxisComb->setObjectName(QStringLiteral("checkBox_AxisComb"));
        checkBox_AxisComb->setGeometry(QRect(20, 330, 111, 17));
        checkBox_AxisComb->setFont(font);
        comboBox_AxisCombBegin = new QComboBox(tab);
        comboBox_AxisCombBegin->setObjectName(QStringLiteral("comboBox_AxisCombBegin"));
        comboBox_AxisCombBegin->setGeometry(QRect(20, 360, 41, 22));
        comboBox_AxisCombEnd = new QComboBox(tab);
        comboBox_AxisCombEnd->setObjectName(QStringLiteral("comboBox_AxisCombEnd"));
        comboBox_AxisCombEnd->setGeometry(QRect(20, 410, 41, 22));
        horizontalSliderAxisComb = new QSlider(tab);
        horizontalSliderAxisComb->setObjectName(QStringLiteral("horizontalSliderAxisComb"));
        horizontalSliderAxisComb->setGeometry(QRect(210, 480, 391, 20));
        horizontalSliderAxisComb->setAutoFillBackground(false);
        horizontalSliderAxisComb->setMaximum(100);
        horizontalSliderAxisComb->setValue(50);
        horizontalSliderAxisComb->setOrientation(Qt::Horizontal);
        horizontalSliderAxisComb->setInvertedAppearance(false);
        horizontalSliderAxisComb->setInvertedControls(false);
        horizontalSliderAxisComb->setTickPosition(QSlider::TicksAbove);
        horizontalSliderAxisComb->setTickInterval(10);
        label_AxisComb1 = new QLabel(tab);
        label_AxisComb1->setObjectName(QStringLiteral("label_AxisComb1"));
        label_AxisComb1->setGeometry(QRect(235, 450, 31, 20));
        label_AxisComb2 = new QLabel(tab);
        label_AxisComb2->setObjectName(QStringLiteral("label_AxisComb2"));
        label_AxisComb2->setGeometry(QRect(455, 450, 31, 20));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(210, 450, 21, 20));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(265, 450, 101, 20));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(430, 450, 21, 20));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(485, 450, 111, 20));
        label_AxisCombPin1 = new QLabel(tab);
        label_AxisCombPin1->setObjectName(QStringLiteral("label_AxisCombPin1"));
        label_AxisCombPin1->setGeometry(QRect(370, 450, 21, 20));
        label_AxisCombPin2 = new QLabel(tab);
        label_AxisCombPin2->setObjectName(QStringLiteral("label_AxisCombPin2"));
        label_AxisCombPin2->setGeometry(QRect(590, 450, 21, 20));
        radioButtonCoopwoork = new QRadioButton(tab);
        radioButtonCoopwoork->setObjectName(QStringLiteral("radioButtonCoopwoork"));
        radioButtonCoopwoork->setGeometry(QRect(80, 460, 111, 17));
        radioButtonCoopwoork->setChecked(true);
        radioButtonEachonhisown = new QRadioButton(tab);
        radioButtonEachonhisown->setObjectName(QStringLiteral("radioButtonEachonhisown"));
        radioButtonEachonhisown->setGeometry(QRect(80, 480, 101, 17));
        widget_axis1 = new OSHaxiswca(tab);
        widget_axis1->setObjectName(QStringLiteral("widget_axis1"));
        widget_axis1->setGeometry(QRect(80, 10, 750, 43));
        widget_axis1->setMouseTracking(true);
        widget_axis2 = new OSHaxiswca(tab);
        widget_axis2->setObjectName(QStringLiteral("widget_axis2"));
        widget_axis2->setGeometry(QRect(80, 60, 750, 43));
        widget_axis2->setMouseTracking(true);
        widget_axis3 = new OSHaxiswca(tab);
        widget_axis3->setObjectName(QStringLiteral("widget_axis3"));
        widget_axis3->setGeometry(QRect(80, 110, 750, 43));
        widget_axis3->setMouseTracking(true);
        widget_axis4 = new OSHaxiswca(tab);
        widget_axis4->setObjectName(QStringLiteral("widget_axis4"));
        widget_axis4->setGeometry(QRect(80, 160, 750, 43));
        widget_axis4->setMouseTracking(true);
        widget_axis5 = new OSHaxiswca(tab);
        widget_axis5->setObjectName(QStringLiteral("widget_axis5"));
        widget_axis5->setGeometry(QRect(80, 210, 750, 43));
        widget_axis5->setMouseTracking(true);
        widget_axis6 = new OSHaxiswca(tab);
        widget_axis6->setObjectName(QStringLiteral("widget_axis6"));
        widget_axis6->setGeometry(QRect(80, 260, 750, 43));
        widget_axis6->setMouseTracking(true);
        widget_axisComb1 = new OSHaxiswca(tab);
        widget_axisComb1->setObjectName(QStringLiteral("widget_axisComb1"));
        widget_axisComb1->setGeometry(QRect(80, 350, 750, 43));
        widget_axisComb1->setMouseTracking(true);
        widget_axisComb2 = new OSHaxiswca(tab);
        widget_axisComb2->setObjectName(QStringLiteral("widget_axisComb2"));
        widget_axisComb2->setGeometry(QRect(80, 400, 750, 43));
        widget_axisComb2->setMouseTracking(true);
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        labelButt_16 = new QLabel(tab_3);
        labelButt_16->setObjectName(QStringLiteral("labelButt_16"));
        labelButt_16->setGeometry(QRect(30, 150, 51, 41));
        labelButt_16->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_16->setScaledContents(true);
        labelButt_1 = new QLabel(tab_3);
        labelButt_1->setObjectName(QStringLiteral("labelButt_1"));
        labelButt_1->setGeometry(QRect(110, 50, 51, 41));
        labelButt_1->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_1->setScaledContents(true);
        labelButt_2 = new QLabel(tab_3);
        labelButt_2->setObjectName(QStringLiteral("labelButt_2"));
        labelButt_2->setGeometry(QRect(190, 50, 51, 41));
        labelButt_2->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_2->setScaledContents(true);
        labelButt_3 = new QLabel(tab_3);
        labelButt_3->setObjectName(QStringLiteral("labelButt_3"));
        labelButt_3->setGeometry(QRect(270, 50, 51, 41));
        labelButt_3->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_3->setScaledContents(true);
        labelButt_4 = new QLabel(tab_3);
        labelButt_4->setObjectName(QStringLiteral("labelButt_4"));
        labelButt_4->setGeometry(QRect(350, 50, 51, 41));
        labelButt_4->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_4->setScaledContents(true);
        labelButt_5 = new QLabel(tab_3);
        labelButt_5->setObjectName(QStringLiteral("labelButt_5"));
        labelButt_5->setGeometry(QRect(430, 50, 51, 41));
        labelButt_5->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_5->setScaledContents(true);
        labelButt_6 = new QLabel(tab_3);
        labelButt_6->setObjectName(QStringLiteral("labelButt_6"));
        labelButt_6->setGeometry(QRect(510, 50, 51, 41));
        labelButt_6->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_6->setScaledContents(true);
        labelButt_7 = new QLabel(tab_3);
        labelButt_7->setObjectName(QStringLiteral("labelButt_7"));
        labelButt_7->setGeometry(QRect(590, 50, 51, 41));
        labelButt_7->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_7->setScaledContents(true);
        labelButt_24 = new QLabel(tab_3);
        labelButt_24->setObjectName(QStringLiteral("labelButt_24"));
        labelButt_24->setGeometry(QRect(30, 200, 51, 41));
        labelButt_24->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_24->setScaledContents(true);
        labelButt_9 = new QLabel(tab_3);
        labelButt_9->setObjectName(QStringLiteral("labelButt_9"));
        labelButt_9->setGeometry(QRect(110, 100, 51, 41));
        labelButt_9->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_9->setScaledContents(true);
        labelButt_10 = new QLabel(tab_3);
        labelButt_10->setObjectName(QStringLiteral("labelButt_10"));
        labelButt_10->setGeometry(QRect(190, 100, 51, 41));
        labelButt_10->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_10->setScaledContents(true);
        labelButt_11 = new QLabel(tab_3);
        labelButt_11->setObjectName(QStringLiteral("labelButt_11"));
        labelButt_11->setGeometry(QRect(270, 100, 51, 41));
        labelButt_11->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_11->setScaledContents(true);
        labelButt_12 = new QLabel(tab_3);
        labelButt_12->setObjectName(QStringLiteral("labelButt_12"));
        labelButt_12->setGeometry(QRect(350, 100, 51, 41));
        labelButt_12->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_12->setScaledContents(true);
        labelButt_13 = new QLabel(tab_3);
        labelButt_13->setObjectName(QStringLiteral("labelButt_13"));
        labelButt_13->setGeometry(QRect(430, 100, 51, 41));
        labelButt_13->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_13->setScaledContents(true);
        labelButt_14 = new QLabel(tab_3);
        labelButt_14->setObjectName(QStringLiteral("labelButt_14"));
        labelButt_14->setGeometry(QRect(510, 100, 51, 41));
        labelButt_14->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_14->setScaledContents(true);
        labelButt_15 = new QLabel(tab_3);
        labelButt_15->setObjectName(QStringLiteral("labelButt_15"));
        labelButt_15->setGeometry(QRect(590, 100, 51, 41));
        labelButt_15->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_15->setScaledContents(true);
        labelButt_32 = new QLabel(tab_3);
        labelButt_32->setObjectName(QStringLiteral("labelButt_32"));
        labelButt_32->setGeometry(QRect(30, 250, 51, 41));
        labelButt_32->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_32->setScaledContents(true);
        labelButt_17 = new QLabel(tab_3);
        labelButt_17->setObjectName(QStringLiteral("labelButt_17"));
        labelButt_17->setGeometry(QRect(110, 150, 51, 41));
        labelButt_17->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_17->setScaledContents(true);
        labelButt_18 = new QLabel(tab_3);
        labelButt_18->setObjectName(QStringLiteral("labelButt_18"));
        labelButt_18->setGeometry(QRect(190, 150, 51, 41));
        labelButt_18->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_18->setScaledContents(true);
        labelButt_19 = new QLabel(tab_3);
        labelButt_19->setObjectName(QStringLiteral("labelButt_19"));
        labelButt_19->setGeometry(QRect(270, 150, 51, 41));
        labelButt_19->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_19->setScaledContents(true);
        labelButt_20 = new QLabel(tab_3);
        labelButt_20->setObjectName(QStringLiteral("labelButt_20"));
        labelButt_20->setGeometry(QRect(350, 150, 51, 41));
        labelButt_20->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_20->setScaledContents(true);
        labelButt_21 = new QLabel(tab_3);
        labelButt_21->setObjectName(QStringLiteral("labelButt_21"));
        labelButt_21->setGeometry(QRect(430, 150, 51, 41));
        labelButt_21->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_21->setScaledContents(true);
        labelButt_22 = new QLabel(tab_3);
        labelButt_22->setObjectName(QStringLiteral("labelButt_22"));
        labelButt_22->setGeometry(QRect(510, 150, 51, 41));
        labelButt_22->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_22->setScaledContents(true);
        labelButt_23 = new QLabel(tab_3);
        labelButt_23->setObjectName(QStringLiteral("labelButt_23"));
        labelButt_23->setGeometry(QRect(590, 150, 51, 41));
        labelButt_23->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_23->setScaledContents(true);
        labelButt_40 = new QLabel(tab_3);
        labelButt_40->setObjectName(QStringLiteral("labelButt_40"));
        labelButt_40->setGeometry(QRect(30, 300, 51, 41));
        labelButt_40->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_40->setScaledContents(true);
        labelButt_25 = new QLabel(tab_3);
        labelButt_25->setObjectName(QStringLiteral("labelButt_25"));
        labelButt_25->setGeometry(QRect(110, 200, 51, 41));
        labelButt_25->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_25->setScaledContents(true);
        labelButt_26 = new QLabel(tab_3);
        labelButt_26->setObjectName(QStringLiteral("labelButt_26"));
        labelButt_26->setGeometry(QRect(190, 200, 51, 41));
        labelButt_26->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_26->setScaledContents(true);
        labelButt_27 = new QLabel(tab_3);
        labelButt_27->setObjectName(QStringLiteral("labelButt_27"));
        labelButt_27->setGeometry(QRect(270, 200, 51, 41));
        labelButt_27->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_27->setScaledContents(true);
        labelButt_28 = new QLabel(tab_3);
        labelButt_28->setObjectName(QStringLiteral("labelButt_28"));
        labelButt_28->setGeometry(QRect(350, 200, 51, 41));
        labelButt_28->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_28->setScaledContents(true);
        labelButt_29 = new QLabel(tab_3);
        labelButt_29->setObjectName(QStringLiteral("labelButt_29"));
        labelButt_29->setGeometry(QRect(430, 200, 51, 41));
        labelButt_29->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_29->setScaledContents(true);
        labelButt_30 = new QLabel(tab_3);
        labelButt_30->setObjectName(QStringLiteral("labelButt_30"));
        labelButt_30->setGeometry(QRect(510, 200, 51, 41));
        labelButt_30->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_30->setScaledContents(true);
        labelButt_31 = new QLabel(tab_3);
        labelButt_31->setObjectName(QStringLiteral("labelButt_31"));
        labelButt_31->setGeometry(QRect(590, 200, 51, 41));
        labelButt_31->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_31->setScaledContents(true);
        labelButt_48 = new QLabel(tab_3);
        labelButt_48->setObjectName(QStringLiteral("labelButt_48"));
        labelButt_48->setGeometry(QRect(30, 350, 51, 41));
        labelButt_48->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_48->setScaledContents(true);
        labelButt_33 = new QLabel(tab_3);
        labelButt_33->setObjectName(QStringLiteral("labelButt_33"));
        labelButt_33->setGeometry(QRect(110, 250, 51, 41));
        labelButt_33->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_33->setScaledContents(true);
        labelButt_34 = new QLabel(tab_3);
        labelButt_34->setObjectName(QStringLiteral("labelButt_34"));
        labelButt_34->setGeometry(QRect(190, 250, 51, 41));
        labelButt_34->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_34->setScaledContents(true);
        labelButt_35 = new QLabel(tab_3);
        labelButt_35->setObjectName(QStringLiteral("labelButt_35"));
        labelButt_35->setGeometry(QRect(270, 250, 51, 41));
        labelButt_35->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_35->setScaledContents(true);
        labelButt_36 = new QLabel(tab_3);
        labelButt_36->setObjectName(QStringLiteral("labelButt_36"));
        labelButt_36->setGeometry(QRect(350, 250, 51, 41));
        labelButt_36->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_36->setScaledContents(true);
        labelButt_37 = new QLabel(tab_3);
        labelButt_37->setObjectName(QStringLiteral("labelButt_37"));
        labelButt_37->setGeometry(QRect(430, 250, 51, 41));
        labelButt_37->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_37->setScaledContents(true);
        labelButt_38 = new QLabel(tab_3);
        labelButt_38->setObjectName(QStringLiteral("labelButt_38"));
        labelButt_38->setGeometry(QRect(510, 250, 51, 41));
        labelButt_38->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_38->setScaledContents(true);
        labelButt_39 = new QLabel(tab_3);
        labelButt_39->setObjectName(QStringLiteral("labelButt_39"));
        labelButt_39->setGeometry(QRect(590, 250, 51, 41));
        labelButt_39->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_39->setScaledContents(true);
        labelButt_56 = new QLabel(tab_3);
        labelButt_56->setObjectName(QStringLiteral("labelButt_56"));
        labelButt_56->setGeometry(QRect(30, 400, 51, 41));
        labelButt_56->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_56->setScaledContents(true);
        labelButt_41 = new QLabel(tab_3);
        labelButt_41->setObjectName(QStringLiteral("labelButt_41"));
        labelButt_41->setGeometry(QRect(110, 300, 51, 41));
        labelButt_41->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_41->setScaledContents(true);
        labelButt_42 = new QLabel(tab_3);
        labelButt_42->setObjectName(QStringLiteral("labelButt_42"));
        labelButt_42->setGeometry(QRect(190, 300, 51, 41));
        labelButt_42->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_42->setScaledContents(true);
        labelButt_43 = new QLabel(tab_3);
        labelButt_43->setObjectName(QStringLiteral("labelButt_43"));
        labelButt_43->setGeometry(QRect(270, 300, 51, 41));
        labelButt_43->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_43->setScaledContents(true);
        labelButt_44 = new QLabel(tab_3);
        labelButt_44->setObjectName(QStringLiteral("labelButt_44"));
        labelButt_44->setGeometry(QRect(350, 300, 51, 41));
        labelButt_44->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_44->setScaledContents(true);
        labelButt_45 = new QLabel(tab_3);
        labelButt_45->setObjectName(QStringLiteral("labelButt_45"));
        labelButt_45->setGeometry(QRect(430, 300, 51, 41));
        labelButt_45->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_45->setScaledContents(true);
        labelButt_46 = new QLabel(tab_3);
        labelButt_46->setObjectName(QStringLiteral("labelButt_46"));
        labelButt_46->setGeometry(QRect(510, 300, 51, 41));
        labelButt_46->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_46->setScaledContents(true);
        labelButt_47 = new QLabel(tab_3);
        labelButt_47->setObjectName(QStringLiteral("labelButt_47"));
        labelButt_47->setGeometry(QRect(590, 300, 51, 41));
        labelButt_47->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_47->setScaledContents(true);
        labelButt_8 = new QLabel(tab_3);
        labelButt_8->setObjectName(QStringLiteral("labelButt_8"));
        labelButt_8->setGeometry(QRect(30, 100, 51, 41));
        labelButt_8->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_8->setScaledContents(true);
        labelButt_0 = new QLabel(tab_3);
        labelButt_0->setObjectName(QStringLiteral("labelButt_0"));
        labelButt_0->setGeometry(QRect(30, 50, 51, 41));
        labelButt_0->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_0->setScaledContents(true);
        labelButt_49 = new QLabel(tab_3);
        labelButt_49->setObjectName(QStringLiteral("labelButt_49"));
        labelButt_49->setGeometry(QRect(110, 350, 51, 41));
        labelButt_49->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_49->setScaledContents(true);
        labelButt_57 = new QLabel(tab_3);
        labelButt_57->setObjectName(QStringLiteral("labelButt_57"));
        labelButt_57->setGeometry(QRect(110, 400, 51, 41));
        labelButt_57->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_57->setScaledContents(true);
        labelButt_50 = new QLabel(tab_3);
        labelButt_50->setObjectName(QStringLiteral("labelButt_50"));
        labelButt_50->setGeometry(QRect(190, 350, 51, 41));
        labelButt_50->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_50->setScaledContents(true);
        labelButt_58 = new QLabel(tab_3);
        labelButt_58->setObjectName(QStringLiteral("labelButt_58"));
        labelButt_58->setGeometry(QRect(190, 400, 51, 41));
        labelButt_58->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_58->setScaledContents(true);
        labelButt_51 = new QLabel(tab_3);
        labelButt_51->setObjectName(QStringLiteral("labelButt_51"));
        labelButt_51->setGeometry(QRect(270, 350, 51, 41));
        labelButt_51->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_51->setScaledContents(true);
        labelButt_59 = new QLabel(tab_3);
        labelButt_59->setObjectName(QStringLiteral("labelButt_59"));
        labelButt_59->setGeometry(QRect(270, 400, 51, 41));
        labelButt_59->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_59->setScaledContents(true);
        labelButt_52 = new QLabel(tab_3);
        labelButt_52->setObjectName(QStringLiteral("labelButt_52"));
        labelButt_52->setGeometry(QRect(350, 350, 51, 41));
        labelButt_52->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_52->setScaledContents(true);
        labelButt_60 = new QLabel(tab_3);
        labelButt_60->setObjectName(QStringLiteral("labelButt_60"));
        labelButt_60->setGeometry(QRect(350, 400, 51, 41));
        labelButt_60->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_60->setScaledContents(true);
        labelButt_53 = new QLabel(tab_3);
        labelButt_53->setObjectName(QStringLiteral("labelButt_53"));
        labelButt_53->setGeometry(QRect(430, 350, 51, 41));
        labelButt_53->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_53->setScaledContents(true);
        labelButt_61 = new QLabel(tab_3);
        labelButt_61->setObjectName(QStringLiteral("labelButt_61"));
        labelButt_61->setGeometry(QRect(430, 400, 51, 41));
        labelButt_61->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_61->setScaledContents(true);
        labelButt_54 = new QLabel(tab_3);
        labelButt_54->setObjectName(QStringLiteral("labelButt_54"));
        labelButt_54->setGeometry(QRect(510, 350, 51, 41));
        labelButt_54->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_54->setScaledContents(true);
        labelButt_62 = new QLabel(tab_3);
        labelButt_62->setObjectName(QStringLiteral("labelButt_62"));
        labelButt_62->setGeometry(QRect(510, 400, 51, 41));
        labelButt_62->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_62->setScaledContents(true);
        labelButt_55 = new QLabel(tab_3);
        labelButt_55->setObjectName(QStringLiteral("labelButt_55"));
        labelButt_55->setGeometry(QRect(590, 350, 51, 41));
        labelButt_55->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_55->setScaledContents(true);
        labelButt_63 = new QLabel(tab_3);
        labelButt_63->setObjectName(QStringLiteral("labelButt_63"));
        labelButt_63->setGeometry(QRect(590, 400, 51, 41));
        labelButt_63->setPixmap(QPixmap(QString::fromUtf8(":/Images/OFF.png")));
        labelButt_63->setScaledContents(true);
        label_117 = new QLabel(tab_3);
        label_117->setObjectName(QStringLiteral("label_117"));
        label_117->setGeometry(QRect(20, 10, 131, 21));
        QFont font5;
        font5.setPointSize(10);
        font5.setBold(true);
        font5.setItalic(false);
        font5.setWeight(75);
        label_117->setFont(font5);
        label_POV1 = new QLabel(tab_3);
        label_POV1->setObjectName(QStringLiteral("label_POV1"));
        label_POV1->setEnabled(false);
        label_POV1->setGeometry(QRect(710, 50, 81, 81));
        label_POV1->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV1->setScaledContents(true);
        label_POV2 = new QLabel(tab_3);
        label_POV2->setObjectName(QStringLiteral("label_POV2"));
        label_POV2->setEnabled(false);
        label_POV2->setGeometry(QRect(710, 150, 81, 81));
        label_POV2->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV2->setScaledContents(true);
        label_POV3 = new QLabel(tab_3);
        label_POV3->setObjectName(QStringLiteral("label_POV3"));
        label_POV3->setEnabled(false);
        label_POV3->setGeometry(QRect(710, 250, 81, 81));
        label_POV3->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV3->setScaledContents(true);
        label_POV4 = new QLabel(tab_3);
        label_POV4->setObjectName(QStringLiteral("label_POV4"));
        label_POV4->setEnabled(false);
        label_POV4->setGeometry(QRect(710, 350, 81, 81));
        label_POV4->setPixmap(QPixmap(QString::fromUtf8(":/Images/dpad.png")));
        label_POV4->setScaledContents(true);
        checkBox_POV1 = new QCheckBox(tab_3);
        checkBox_POV1->setObjectName(QStringLiteral("checkBox_POV1"));
        checkBox_POV1->setGeometry(QRect(690, 30, 81, 17));
        checkBox_POV2 = new QCheckBox(tab_3);
        checkBox_POV2->setObjectName(QStringLiteral("checkBox_POV2"));
        checkBox_POV2->setGeometry(QRect(690, 130, 81, 17));
        checkBox_POV3 = new QCheckBox(tab_3);
        checkBox_POV3->setObjectName(QStringLiteral("checkBox_POV3"));
        checkBox_POV3->setGeometry(QRect(690, 230, 81, 17));
        checkBox_POV4 = new QCheckBox(tab_3);
        checkBox_POV4->setObjectName(QStringLiteral("checkBox_POV4"));
        checkBox_POV4->setGeometry(QRect(690, 330, 81, 17));
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(40, 480, 141, 16));
        label_8->setFont(font);
        horiSlider_A2B = new QSlider(tab_3);
        horiSlider_A2B->setObjectName(QStringLiteral("horiSlider_A2B"));
        horiSlider_A2B->setGeometry(QRect(230, 480, 421, 22));
        horiSlider_A2B->setMaximum(4095);
        horiSlider_A2B->setOrientation(Qt::Horizontal);
        horiSlider_A2B->setTickPosition(QSlider::TicksAbove);
        horiSlider_A2B->setTickInterval(200);
        label_9 = new QLabel(tab_3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(660, 480, 47, 13));
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(210, 480, 16, 16));
        tabWidget->addTab(tab_3, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_SE1 = new QLabel(tab_5);
        label_SE1->setObjectName(QStringLiteral("label_SE1"));
        label_SE1->setGeometry(QRect(10, 30, 91, 71));
        label_SE1->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE1->setScaledContents(true);
        comboBox_SEA1 = new QComboBox(tab_5);
        comboBox_SEA1->setObjectName(QStringLiteral("comboBox_SEA1"));
        comboBox_SEA1->setGeometry(QRect(108, 30, 101, 22));
        comboBox_SEB1 = new QComboBox(tab_5);
        comboBox_SEB1->setObjectName(QStringLiteral("comboBox_SEB1"));
        comboBox_SEB1->setGeometry(QRect(108, 80, 101, 22));
        label_SE1_CPin = new QLabel(tab_5);
        label_SE1_CPin->setObjectName(QStringLiteral("label_SE1_CPin"));
        label_SE1_CPin->setGeometry(QRect(110, 60, 47, 13));
        label_SE2 = new QLabel(tab_5);
        label_SE2->setObjectName(QStringLiteral("label_SE2"));
        label_SE2->setGeometry(QRect(10, 140, 91, 71));
        label_SE2->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE2->setScaledContents(true);
        comboBox_SEA2 = new QComboBox(tab_5);
        comboBox_SEA2->setObjectName(QStringLiteral("comboBox_SEA2"));
        comboBox_SEA2->setGeometry(QRect(108, 140, 101, 22));
        label_SE2_CPin = new QLabel(tab_5);
        label_SE2_CPin->setObjectName(QStringLiteral("label_SE2_CPin"));
        label_SE2_CPin->setGeometry(QRect(110, 170, 47, 13));
        comboBox_SEB2 = new QComboBox(tab_5);
        comboBox_SEB2->setObjectName(QStringLiteral("comboBox_SEB2"));
        comboBox_SEB2->setGeometry(QRect(108, 190, 101, 22));
        label_SE3 = new QLabel(tab_5);
        label_SE3->setObjectName(QStringLiteral("label_SE3"));
        label_SE3->setGeometry(QRect(10, 250, 91, 71));
        label_SE3->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE3->setScaledContents(true);
        comboBox_SEA3 = new QComboBox(tab_5);
        comboBox_SEA3->setObjectName(QStringLiteral("comboBox_SEA3"));
        comboBox_SEA3->setGeometry(QRect(108, 250, 101, 22));
        label_SE3_CPin = new QLabel(tab_5);
        label_SE3_CPin->setObjectName(QStringLiteral("label_SE3_CPin"));
        label_SE3_CPin->setGeometry(QRect(110, 280, 47, 13));
        comboBox_SEB3 = new QComboBox(tab_5);
        comboBox_SEB3->setObjectName(QStringLiteral("comboBox_SEB3"));
        comboBox_SEB3->setGeometry(QRect(108, 300, 101, 22));
        label_SE4 = new QLabel(tab_5);
        label_SE4->setObjectName(QStringLiteral("label_SE4"));
        label_SE4->setGeometry(QRect(10, 360, 91, 71));
        label_SE4->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE4->setScaledContents(true);
        comboBox_SEA4 = new QComboBox(tab_5);
        comboBox_SEA4->setObjectName(QStringLiteral("comboBox_SEA4"));
        comboBox_SEA4->setGeometry(QRect(108, 360, 101, 22));
        comboBox_SEB4 = new QComboBox(tab_5);
        comboBox_SEB4->setObjectName(QStringLiteral("comboBox_SEB4"));
        comboBox_SEB4->setGeometry(QRect(108, 410, 101, 22));
        label_SE4_CPin = new QLabel(tab_5);
        label_SE4_CPin->setObjectName(QStringLiteral("label_SE4_CPin"));
        label_SE4_CPin->setGeometry(QRect(110, 390, 47, 13));
        label_SE6_CPin = new QLabel(tab_5);
        label_SE6_CPin->setObjectName(QStringLiteral("label_SE6_CPin"));
        label_SE6_CPin->setGeometry(QRect(320, 170, 47, 13));
        comboBox_SEA5 = new QComboBox(tab_5);
        comboBox_SEA5->setObjectName(QStringLiteral("comboBox_SEA5"));
        comboBox_SEA5->setGeometry(QRect(318, 30, 101, 22));
        label_SE5_CPin = new QLabel(tab_5);
        label_SE5_CPin->setObjectName(QStringLiteral("label_SE5_CPin"));
        label_SE5_CPin->setGeometry(QRect(320, 60, 47, 13));
        comboBox_SEA7 = new QComboBox(tab_5);
        comboBox_SEA7->setObjectName(QStringLiteral("comboBox_SEA7"));
        comboBox_SEA7->setGeometry(QRect(318, 250, 101, 22));
        label_SE8 = new QLabel(tab_5);
        label_SE8->setObjectName(QStringLiteral("label_SE8"));
        label_SE8->setGeometry(QRect(220, 360, 91, 71));
        label_SE8->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE8->setScaledContents(true);
        comboBox_SEB5 = new QComboBox(tab_5);
        comboBox_SEB5->setObjectName(QStringLiteral("comboBox_SEB5"));
        comboBox_SEB5->setGeometry(QRect(318, 80, 101, 22));
        comboBox_SEB6 = new QComboBox(tab_5);
        comboBox_SEB6->setObjectName(QStringLiteral("comboBox_SEB6"));
        comboBox_SEB6->setGeometry(QRect(318, 190, 101, 22));
        label_SE7_CPin = new QLabel(tab_5);
        label_SE7_CPin->setObjectName(QStringLiteral("label_SE7_CPin"));
        label_SE7_CPin->setGeometry(QRect(320, 280, 47, 13));
        label_SE8_CPin = new QLabel(tab_5);
        label_SE8_CPin->setObjectName(QStringLiteral("label_SE8_CPin"));
        label_SE8_CPin->setGeometry(QRect(320, 390, 47, 13));
        comboBox_SEB7 = new QComboBox(tab_5);
        comboBox_SEB7->setObjectName(QStringLiteral("comboBox_SEB7"));
        comboBox_SEB7->setGeometry(QRect(318, 300, 101, 22));
        label_SE6 = new QLabel(tab_5);
        label_SE6->setObjectName(QStringLiteral("label_SE6"));
        label_SE6->setGeometry(QRect(220, 140, 91, 71));
        label_SE6->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE6->setScaledContents(true);
        comboBox_SEA8 = new QComboBox(tab_5);
        comboBox_SEA8->setObjectName(QStringLiteral("comboBox_SEA8"));
        comboBox_SEA8->setGeometry(QRect(318, 360, 101, 22));
        comboBox_SEA6 = new QComboBox(tab_5);
        comboBox_SEA6->setObjectName(QStringLiteral("comboBox_SEA6"));
        comboBox_SEA6->setGeometry(QRect(318, 140, 101, 22));
        comboBox_SEB8 = new QComboBox(tab_5);
        comboBox_SEB8->setObjectName(QStringLiteral("comboBox_SEB8"));
        comboBox_SEB8->setGeometry(QRect(318, 410, 101, 22));
        label_SE7 = new QLabel(tab_5);
        label_SE7->setObjectName(QStringLiteral("label_SE7"));
        label_SE7->setGeometry(QRect(220, 250, 91, 71));
        label_SE7->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE7->setScaledContents(true);
        label_SE5 = new QLabel(tab_5);
        label_SE5->setObjectName(QStringLiteral("label_SE5"));
        label_SE5->setGeometry(QRect(220, 30, 91, 71));
        label_SE5->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE5->setScaledContents(true);
        label_SE10_CPin = new QLabel(tab_5);
        label_SE10_CPin->setObjectName(QStringLiteral("label_SE10_CPin"));
        label_SE10_CPin->setGeometry(QRect(530, 170, 47, 13));
        comboBox_SEA9 = new QComboBox(tab_5);
        comboBox_SEA9->setObjectName(QStringLiteral("comboBox_SEA9"));
        comboBox_SEA9->setGeometry(QRect(528, 30, 101, 22));
        label_SE9_CPin = new QLabel(tab_5);
        label_SE9_CPin->setObjectName(QStringLiteral("label_SE9_CPin"));
        label_SE9_CPin->setGeometry(QRect(530, 60, 47, 13));
        comboBox_SEA11 = new QComboBox(tab_5);
        comboBox_SEA11->setObjectName(QStringLiteral("comboBox_SEA11"));
        comboBox_SEA11->setGeometry(QRect(528, 250, 101, 22));
        label_SE12 = new QLabel(tab_5);
        label_SE12->setObjectName(QStringLiteral("label_SE12"));
        label_SE12->setGeometry(QRect(430, 360, 91, 71));
        label_SE12->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE12->setScaledContents(true);
        comboBox_SEB9 = new QComboBox(tab_5);
        comboBox_SEB9->setObjectName(QStringLiteral("comboBox_SEB9"));
        comboBox_SEB9->setGeometry(QRect(528, 80, 101, 22));
        comboBox_SEB10 = new QComboBox(tab_5);
        comboBox_SEB10->setObjectName(QStringLiteral("comboBox_SEB10"));
        comboBox_SEB10->setGeometry(QRect(528, 190, 101, 22));
        label_SE11_CPin = new QLabel(tab_5);
        label_SE11_CPin->setObjectName(QStringLiteral("label_SE11_CPin"));
        label_SE11_CPin->setGeometry(QRect(530, 280, 47, 13));
        label_SE12_CPin = new QLabel(tab_5);
        label_SE12_CPin->setObjectName(QStringLiteral("label_SE12_CPin"));
        label_SE12_CPin->setGeometry(QRect(530, 390, 47, 13));
        comboBox_SEB11 = new QComboBox(tab_5);
        comboBox_SEB11->setObjectName(QStringLiteral("comboBox_SEB11"));
        comboBox_SEB11->setGeometry(QRect(528, 300, 101, 22));
        label_SE10 = new QLabel(tab_5);
        label_SE10->setObjectName(QStringLiteral("label_SE10"));
        label_SE10->setGeometry(QRect(430, 140, 91, 71));
        label_SE10->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE10->setScaledContents(true);
        comboBox_SEA12 = new QComboBox(tab_5);
        comboBox_SEA12->setObjectName(QStringLiteral("comboBox_SEA12"));
        comboBox_SEA12->setGeometry(QRect(528, 360, 101, 22));
        comboBox_SEA10 = new QComboBox(tab_5);
        comboBox_SEA10->setObjectName(QStringLiteral("comboBox_SEA10"));
        comboBox_SEA10->setGeometry(QRect(528, 140, 101, 22));
        comboBox_SEB12 = new QComboBox(tab_5);
        comboBox_SEB12->setObjectName(QStringLiteral("comboBox_SEB12"));
        comboBox_SEB12->setGeometry(QRect(528, 410, 101, 22));
        label_SE11 = new QLabel(tab_5);
        label_SE11->setObjectName(QStringLiteral("label_SE11"));
        label_SE11->setGeometry(QRect(430, 250, 91, 71));
        label_SE11->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE11->setScaledContents(true);
        label_SE9 = new QLabel(tab_5);
        label_SE9->setObjectName(QStringLiteral("label_SE9"));
        label_SE9->setGeometry(QRect(430, 30, 91, 71));
        label_SE9->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE9->setScaledContents(true);
        label_SE14_CPin = new QLabel(tab_5);
        label_SE14_CPin->setObjectName(QStringLiteral("label_SE14_CPin"));
        label_SE14_CPin->setGeometry(QRect(742, 390, 47, 13));
        comboBox_SEA13 = new QComboBox(tab_5);
        comboBox_SEA13->setObjectName(QStringLiteral("comboBox_SEA13"));
        comboBox_SEA13->setGeometry(QRect(740, 250, 101, 22));
        label_SE13_CPin = new QLabel(tab_5);
        label_SE13_CPin->setObjectName(QStringLiteral("label_SE13_CPin"));
        label_SE13_CPin->setGeometry(QRect(742, 280, 47, 13));
        comboBox_SEB13 = new QComboBox(tab_5);
        comboBox_SEB13->setObjectName(QStringLiteral("comboBox_SEB13"));
        comboBox_SEB13->setGeometry(QRect(740, 300, 101, 22));
        comboBox_SEB14 = new QComboBox(tab_5);
        comboBox_SEB14->setObjectName(QStringLiteral("comboBox_SEB14"));
        comboBox_SEB14->setGeometry(QRect(740, 410, 101, 22));
        label_SE14 = new QLabel(tab_5);
        label_SE14->setObjectName(QStringLiteral("label_SE14"));
        label_SE14->setGeometry(QRect(640, 360, 91, 71));
        label_SE14->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE14->setScaledContents(true);
        comboBox_SEA14 = new QComboBox(tab_5);
        comboBox_SEA14->setObjectName(QStringLiteral("comboBox_SEA14"));
        comboBox_SEA14->setGeometry(QRect(740, 360, 101, 22));
        label_SE13 = new QLabel(tab_5);
        label_SE13->setObjectName(QStringLiteral("label_SE13"));
        label_SE13->setGeometry(QRect(640, 250, 91, 71));
        label_SE13->setPixmap(QPixmap(QString::fromUtf8(":/Images/1053081_zps20151924.jpg")));
        label_SE13->setScaledContents(true);
        label_ZeroSglEncoders = new QLabel(tab_5);
        label_ZeroSglEncoders->setObjectName(QStringLiteral("label_ZeroSglEncoders"));
        label_ZeroSglEncoders->setGeometry(QRect(60, 10, 451, 41));
        label_2 = new QLabel(tab_5);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(660, 20, 161, 211));
        tabWidget->addTab(tab_5, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_54 = new QLabel(tab_4);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(140, 260, 491, 16));
        label_55 = new QLabel(tab_4);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(140, 290, 341, 16));
        label_56 = new QLabel(tab_4);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(140, 320, 281, 16));
        label_57 = new QLabel(tab_4);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(140, 230, 491, 16));
        spinBox__Rot_Press_time = new QSpinBox(tab_4);
        spinBox__Rot_Press_time->setObjectName(QStringLiteral("spinBox__Rot_Press_time"));
        spinBox__Rot_Press_time->setGeometry(QRect(60, 230, 61, 21));
        spinBox__Rot_Press_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox__Rot_Press_time->setMaximum(65535);
        spinBox_RotSwitch_Press_time = new QSpinBox(tab_4);
        spinBox_RotSwitch_Press_time->setObjectName(QStringLiteral("spinBox_RotSwitch_Press_time"));
        spinBox_RotSwitch_Press_time->setGeometry(QRect(60, 260, 61, 21));
        spinBox_RotSwitch_Press_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_RotSwitch_Press_time->setMaximum(65535);
        spinBox_Rot_Debounce_time = new QSpinBox(tab_4);
        spinBox_Rot_Debounce_time->setObjectName(QStringLiteral("spinBox_Rot_Debounce_time"));
        spinBox_Rot_Debounce_time->setGeometry(QRect(60, 290, 61, 21));
        spinBox_Rot_Debounce_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_Rot_Debounce_time->setMaximum(65535);
        spinBox_Button_Debounce_time = new QSpinBox(tab_4);
        spinBox_Button_Debounce_time->setObjectName(QStringLiteral("spinBox_Button_Debounce_time"));
        spinBox_Button_Debounce_time->setGeometry(QRect(60, 320, 61, 21));
        spinBox_Button_Debounce_time->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_Button_Debounce_time->setMaximum(65535);
        line = new QFrame(tab_4);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 180, 811, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        spinBox_USB_exchange = new QSpinBox(tab_4);
        spinBox_USB_exchange->setObjectName(QStringLiteral("spinBox_USB_exchange"));
        spinBox_USB_exchange->setGeometry(QRect(60, 90, 61, 21));
        spinBox_USB_exchange->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        spinBox_USB_exchange->setMinimum(1);
        spinBox_USB_exchange->setMaximum(255);
        label_59 = new QLabel(tab_4);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(140, 90, 441, 16));
        lineEdit_Device_ident = new QLineEdit(tab_4);
        lineEdit_Device_ident->setObjectName(QStringLiteral("lineEdit_Device_ident"));
        lineEdit_Device_ident->setGeometry(QRect(52, 60, 71, 20));
        lineEdit_Device_ident->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        lineEdit_Device_ident->setMaxLength(10);
        label_60 = new QLabel(tab_4);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(140, 60, 521, 16));
        tabWidget->addTab(tab_4, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        widget = new oshpincombobox(tab_6);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(110, 110, 281, 51));
        widget_2 = new oshpincombobox(tab_6);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(110, 160, 281, 51));
        widget_3 = new oshpincombobox(tab_6);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(110, 210, 281, 51));
        comboBox = new QComboBox(tab_6);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(100, 40, 201, 22));
        tabWidget->addTab(tab_6, QString());
        saveConfig_Button = new QPushButton(centralWidget);
        saveConfig_Button->setObjectName(QStringLiteral("saveConfig_Button"));
        saveConfig_Button->setGeometry(QRect(10, 200, 151, 41));
        saveConfig_Button->setFont(font);
        saveFile_Button = new QPushButton(centralWidget);
        saveFile_Button->setObjectName(QStringLiteral("saveFile_Button"));
        saveFile_Button->setGeometry(QRect(10, 470, 151, 41));
        saveFile_Button->setFont(font);
        loadFile_Button = new QPushButton(centralWidget);
        loadFile_Button->setObjectName(QStringLiteral("loadFile_Button"));
        loadFile_Button->setGeometry(QRect(10, 420, 151, 41));
        loadFile_Button->setFont(font);
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(880, 0, 101, 20));
        resetConfig_button = new QPushButton(centralWidget);
        resetConfig_button->setObjectName(QStringLiteral("resetConfig_button"));
        resetConfig_button->setGeometry(QRect(10, 310, 151, 41));
        resetConfig_button->setFont(font);
        restoreConfig_button = new QPushButton(centralWidget);
        restoreConfig_button->setObjectName(QStringLiteral("restoreConfig_button"));
        restoreConfig_button->setGeometry(QRect(10, 360, 151, 41));
        restoreConfig_button->setFont(font);
        label_Stud_version = new QLabel(centralWidget);
        label_Stud_version->setObjectName(QStringLiteral("label_Stud_version"));
        label_Stud_version->setGeometry(QRect(980, 0, 31, 21));
        label_58 = new QLabel(centralWidget);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(890, 20, 91, 21));
        label_Firmware_Vers = new QLabel(centralWidget);
        label_Firmware_Vers->setObjectName(QStringLiteral("label_Firmware_Vers"));
        label_Firmware_Vers->setGeometry(QRect(980, 20, 31, 21));
        OSHStudio->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(OSHStudio);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        QFont font6;
        font6.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font6.setPointSize(8);
        font6.setItalic(true);
        statusBar->setFont(font6);
        statusBar->setLayoutDirection(Qt::LeftToRight);
        OSHStudio->setStatusBar(statusBar);

        retranslateUi(OSHStudio);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(OSHStudio);
    } // setupUi

    void retranslateUi(QMainWindow *OSHStudio)
    {
        OSHStudio->setWindowTitle(QApplication::translate("OSHStudio", "OSHStudio", nullptr));
        getConfig_button->setText(QApplication::translate("OSHStudio", "Get Config from Device", nullptr));
        label_35->setText(QApplication::translate("OSHStudio", "Connected Devices:", nullptr));
        label_DevDescImg->setText(QString());
        label_DevDesc->setText(QApplication::translate("OSHStudio", "OpenSimHardware Pedals & Buttons Controller                               (OSH PB Controller)", nullptr));
        label_B11->setText(QApplication::translate("OSHStudio", "B11", nullptr));
        label_A11->setText(QApplication::translate("OSHStudio", "A11", nullptr));
        label_A3->setText(QApplication::translate("OSHStudio", "A3", nullptr));
        label_B13->setText(QApplication::translate("OSHStudio", "B13", nullptr));
        label_A6->setText(QApplication::translate("OSHStudio", "A6", nullptr));
        label_B15->setText(QApplication::translate("OSHStudio", "B15", nullptr));
        label_B3->setText(QApplication::translate("OSHStudio", "B3", nullptr));
        label_B5->setText(QApplication::translate("OSHStudio", "B5", nullptr));
        label_A15->setText(QApplication::translate("OSHStudio", "A15", nullptr));
        groupBox->setTitle(QApplication::translate("OSHStudio", "Current Configuration", nullptr));
        labelHelp->setText(QString());
        label_C14->setText(QApplication::translate("OSHStudio", "C14", nullptr));
        label_B6->setText(QApplication::translate("OSHStudio", "B6", nullptr));
        label_A2->setText(QApplication::translate("OSHStudio", "A2", nullptr));
        label_B1->setText(QApplication::translate("OSHStudio", "B1", nullptr));
        label_B7->setText(QApplication::translate("OSHStudio", "B7", nullptr));
        label_A0->setText(QApplication::translate("OSHStudio", "A0", nullptr));
        label_A4->setText(QApplication::translate("OSHStudio", "A4", nullptr));
        label_A7->setText(QApplication::translate("OSHStudio", "A7", nullptr));
        label_B8->setText(QApplication::translate("OSHStudio", "B8", nullptr));
        label_A9->setText(QApplication::translate("OSHStudio", "A9", nullptr));
        label_B0->setText(QApplication::translate("OSHStudio", "B0", nullptr));
        label->setText(QString());
        label_C15->setText(QApplication::translate("OSHStudio", "C15", nullptr));
        label_A5->setText(QApplication::translate("OSHStudio", "A5", nullptr));
        label_B4->setText(QApplication::translate("OSHStudio", "B4", nullptr));
        label_B12->setText(QApplication::translate("OSHStudio", "B12", nullptr));
        label_A8->setText(QApplication::translate("OSHStudio", "A8", nullptr));
        label_B14->setText(QApplication::translate("OSHStudio", "B14", nullptr));
        label_A1->setText(QApplication::translate("OSHStudio", "A1", nullptr));
        label_B9->setText(QApplication::translate("OSHStudio", "B9", nullptr));
        label_A10->setText(QApplication::translate("OSHStudio", "A10", nullptr));
        label_A12->setText(QApplication::translate("OSHStudio", "A12", nullptr));
        label_C13->setText(QApplication::translate("OSHStudio", "C13", nullptr));
        label_B10->setText(QApplication::translate("OSHStudio", "B10", nullptr));
        label_3->setText(QApplication::translate("OSHStudio", "Your board type:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("OSHStudio", "Pins Configuration", nullptr));
        label_48->setText(QApplication::translate("OSHStudio", "AXIS1", nullptr));
        label_49->setText(QApplication::translate("OSHStudio", "AXIS2", nullptr));
        label_50->setText(QApplication::translate("OSHStudio", "AXIS3", nullptr));
        label_51->setText(QApplication::translate("OSHStudio", "AXIS4", nullptr));
        label_52->setText(QApplication::translate("OSHStudio", "AXIS5", nullptr));
        label_53->setText(QApplication::translate("OSHStudio", "AXIS6", nullptr));
        checkBox_AxisComb->setText(QApplication::translate("OSHStudio", "Combined Axis", nullptr));
        label_AxisComb1->setText(QString());
        label_AxisComb2->setText(QString());
        label_4->setText(QApplication::translate("OSHStudio", "The", nullptr));
        label_5->setText(QApplication::translate("OSHStudio", "of AXIS6 will be from", nullptr));
        label_6->setText(QApplication::translate("OSHStudio", "The", nullptr));
        label_7->setText(QApplication::translate("OSHStudio", "of AXIS6 will be from", nullptr));
        label_AxisCombPin1->setText(QString());
        label_AxisCombPin2->setText(QString());
        radioButtonCoopwoork->setText(QApplication::translate("OSHStudio", "Cooperative work", nullptr));
        radioButtonEachonhisown->setText(QApplication::translate("OSHStudio", "Each on his own", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("OSHStudio", "Axes Configuration", nullptr));
        labelButt_16->setText(QString());
        labelButt_1->setText(QString());
        labelButt_2->setText(QString());
        labelButt_3->setText(QString());
        labelButt_4->setText(QString());
        labelButt_5->setText(QString());
        labelButt_6->setText(QString());
        labelButt_7->setText(QString());
        labelButt_24->setText(QString());
        labelButt_9->setText(QString());
        labelButt_10->setText(QString());
        labelButt_11->setText(QString());
        labelButt_12->setText(QString());
        labelButt_13->setText(QString());
        labelButt_14->setText(QString());
        labelButt_15->setText(QString());
        labelButt_32->setText(QString());
        labelButt_17->setText(QString());
        labelButt_18->setText(QString());
        labelButt_19->setText(QString());
        labelButt_20->setText(QString());
        labelButt_21->setText(QString());
        labelButt_22->setText(QString());
        labelButt_23->setText(QString());
        labelButt_40->setText(QString());
        labelButt_25->setText(QString());
        labelButt_26->setText(QString());
        labelButt_27->setText(QString());
        labelButt_28->setText(QString());
        labelButt_29->setText(QString());
        labelButt_30->setText(QString());
        labelButt_31->setText(QString());
        labelButt_48->setText(QString());
        labelButt_33->setText(QString());
        labelButt_34->setText(QString());
        labelButt_35->setText(QString());
        labelButt_36->setText(QString());
        labelButt_37->setText(QString());
        labelButt_38->setText(QString());
        labelButt_39->setText(QString());
        labelButt_56->setText(QString());
        labelButt_41->setText(QString());
        labelButt_42->setText(QString());
        labelButt_43->setText(QString());
        labelButt_44->setText(QString());
        labelButt_45->setText(QString());
        labelButt_46->setText(QString());
        labelButt_47->setText(QString());
        labelButt_8->setText(QString());
        labelButt_0->setText(QString());
        labelButt_49->setText(QString());
        labelButt_57->setText(QString());
        labelButt_50->setText(QString());
        labelButt_58->setText(QString());
        labelButt_51->setText(QString());
        labelButt_59->setText(QString());
        labelButt_52->setText(QString());
        labelButt_60->setText(QString());
        labelButt_53->setText(QString());
        labelButt_61->setText(QString());
        labelButt_54->setText(QString());
        labelButt_62->setText(QString());
        labelButt_55->setText(QString());
        labelButt_63->setText(QString());
        label_117->setText(QApplication::translate("OSHStudio", "Test your buttons", nullptr));
        label_POV1->setText(QString());
        label_POV2->setText(QString());
        label_POV3->setText(QString());
        label_POV4->setText(QString());
        checkBox_POV1->setText(QApplication::translate("OSHStudio", "Enable POV1", nullptr));
        checkBox_POV2->setText(QApplication::translate("OSHStudio", "Enable POV2", nullptr));
        checkBox_POV3->setText(QApplication::translate("OSHStudio", "Enable POV3", nullptr));
        checkBox_POV4->setText(QApplication::translate("OSHStudio", "Enable POV4", nullptr));
        label_8->setText(QApplication::translate("OSHStudio", "Analog to Button Inputs", nullptr));
        label_9->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_10->setText(QApplication::translate("OSHStudio", "0V", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("OSHStudio", "Buttons", nullptr));
        label_SE1->setText(QString());
        label_SE1_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE2->setText(QString());
        label_SE2_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE3->setText(QString());
        label_SE3_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE4->setText(QString());
        label_SE4_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE6_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE5_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE8->setText(QString());
        label_SE7_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE8_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE6->setText(QString());
        label_SE7->setText(QString());
        label_SE5->setText(QString());
        label_SE10_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE9_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE12->setText(QString());
        label_SE11_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE12_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE10->setText(QString());
        label_SE11->setText(QString());
        label_SE9->setText(QString());
        label_SE14_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE13_CPin->setText(QApplication::translate("OSHStudio", "+3.3V", nullptr));
        label_SE14->setText(QString());
        label_SE13->setText(QString());
        label_ZeroSglEncoders->setText(QApplication::translate("OSHStudio", "You don't have configured single encoders in \"Pins Configuration\" Tab. ", nullptr));
        label_2->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("OSHStudio", "Single Encoders Config", nullptr));
        label_54->setText(QApplication::translate("OSHStudio", "Amount of time a button will be pressed when Rotary Switch position changed, ms", nullptr));
        label_55->setText(QApplication::translate("OSHStudio", "Debounce time for Rotary Encoders, ms", nullptr));
        label_56->setText(QApplication::translate("OSHStudio", "Debounce time for Buttons, ms", nullptr));
        label_57->setText(QApplication::translate("OSHStudio", "Amount of time a button will be pressed when Rotary Encoders position changed, ms", nullptr));
        label_59->setText(QApplication::translate("OSHStudio", "USB polling interval, ms. It means USB exchange frequency of", nullptr));
        label_60->setText(QApplication::translate("OSHStudio", "Your identifier for the device, it will appear in Windows as \"OSH PB Controller\"", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("OSHStudio", "Tuning", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("OSHStudio", "Page", nullptr));
        saveConfig_Button->setText(QApplication::translate("OSHStudio", "Save Config to Device", nullptr));
        saveFile_Button->setText(QApplication::translate("OSHStudio", "Save Config to File", nullptr));
        loadFile_Button->setText(QApplication::translate("OSHStudio", "Load Config from File", nullptr));
        label_34->setText(QApplication::translate("OSHStudio", "OSH Studio version:", nullptr));
        resetConfig_button->setText(QApplication::translate("OSHStudio", "Reset All Pins", nullptr));
        restoreConfig_button->setText(QApplication::translate("OSHStudio", "Restore Default Config", nullptr));
        label_Stud_version->setText(QApplication::translate("OSHStudio", "TextLabel", nullptr));
        label_58->setText(QApplication::translate("OSHStudio", "Firmware version:", nullptr));
        label_Firmware_Vers->setText(QApplication::translate("OSHStudio", "t", nullptr));
    } // retranslateUi

};

namespace Ui {
    class OSHStudio: public Ui_OSHStudio {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_OSHSTUDIO_H
